Cray-HPE/csm-rpms

packages/node-image-non-compute-common/base.packages

Releases csm-testing which includes changes for csm-1.2
CASMPET-5003 : AUTOMATION: Refactor goss-k8s-monitoring-url.yaml for Bi-CAN
CASMINST-3526 : Drax: Velero backup failed during automated goss test in k8 nodes

CASMPET-5160 main : Release csm-testing for CASMPET-5003 and CASMINST-3526

---

packages/node-image-non-compute-common/base.packages

Releases csm-testing which includes changes for csm-1.2
CASMPET-5003 : AUTOMATION: Refactor goss-k8s-monitoring-url.yaml for Bi-CAN
CASMINST-3526 : Drax: Velero backup failed during automated goss test in k8 nodes

CASMPET-5160 1.2 : Release csm-testing for CASMPET-5003 and CASMINST-3526

---

packages/node-image-non-compute-common/base.packages

Resolves
* CASMINST-3546 : csi pit validate for k8s has failed

CASMINST-3546 1.2 : csi pit validate for k8s has failed

---

packages/cray-pre-install-toolkit/metal.packages

Generates the metalLB config in the customizations.yaml so the config map can get rendered into the new metallb chart.
This will still generate the metallb.yaml as well until we confirm that the config map within the chart is fully working.
This is backwards compatible.
* Resolves [CASMPET-4873](https://connect.us.cray.com/jira/browse/CASMPET-4873)
* surtur
Generated files with CSI and verified that both the metallb.yaml and customizations.yaml look correct.
I tested both with and without the CHN network defined.
Low risk since we are still generating the metallb.yaml as well.  That can be a fallback.

CASMPET-4873:  Generate metallb config in customizations.yaml

---

packages/node-image-non-compute-common/base.packages

This is the release: https://github.com/Cray-HPE/csm-testing/releases
This includes the fix for:
* CASMINST-3603: ncnhealthchecks failed for goss k8 monitoring URL test case
(cherry picked from commit 225bed242cbf367ff2245fde9b6f5e62dcb8ed40)

CASMINST-3603: Bump goss-servers to 1.8.34

---

packages/node-image-kubernetes/base.packages

This fixes a bug in the barebones image boot test script where the user input for which compute node to use for the test was being ignored.  Without this fix a random compute node was always used, with this fix the user may specify which node to use.
Code PR: https://github.com/Cray-HPE/cms-tools/pull/18
* Resolves [CASMTRIAGE-2732](https://connect.us.cray.com/jira/browse/CASMTRIAGE-2732)
* `Wasp`
I loaded the modified script on wasp and disabled that portion of the script that actually initiates the boot, but kept the argument processing and finding a compute node to use for the test. I verified that when a node is specified on the command line it now flows through to the function that looks for an available node. I also tested scenarios where there is nothing passed in and where an …

CASMTRIAGE-2732 - Fix barebones image boot test script.

---

packages/node-image-kubernetes/base.packages

This fixes the test which is causing the CMS part of the CSM health check procedure to fail on every 1.2 install.
See original PR for details:
https://github.com/Cray-HPE/cms-tools/pull/20
This is ready to be merged, pending approvals.

CASMCMS-7691: Fix broken IMS signing keys test

---

packages/node-image-kubernetes/base.packages

This change updates the HMS CT smoke tests to execute the HSM tests first to more easily and clearly identify discovery-related problems.
* Resolves CASMHMS-5205 in csm-1.2
This change was tested by deploying the updated smoke tests and wrapper script to Wasp, executing them, and verifying that the HSM tests ran first. Failures of the HSM smoke tests were also verified to stop execution of the wrapper script as expected.
Low risk.

CASMHMS-5205 Reorder HMS CT smoke test execution csm-1.2

---

packages/cray-pre-install-toolkit/metal.packages

This just additionally prints the nexus RPM info when `metalid.sh` is invoked.

Mtl 1574 1.2

---

packages/cray-pre-install-toolkit/metal.packages

This just additionally prints the nexus RPM info when `metalid.sh` is invoked.

MTL-1574 print nexus info in metalid.sh

---

packages/cray-pre-install-toolkit/base.packages
packages/cray-pre-install-toolkit/metal.packages

This swaps the old cray-nexus RPM for the new [pit-nexus RPM ](https://github.com/Cray-HPE/pit-nexus), this work is tagged with the recent bugfix for pit-nexus [CASMPET-5173](https://connect.us.cray.com/jira/browse/CASMPET-5173).
Yes.
* Resolves [CASMPET-5173](https://connect.us.cray.com/jira/browse/CASMPET-5173)
* Change will also be needed in `main`
* `redbull`
_How were the changes tested and …

CASMPET-5173 Swap cray-nexus for new pit-nexus

---

packages/node-image-non-compute-common/base.packages

Change timeout from 1000ms to 5000ms to wait longer for output to
return. In many cases output will emit before 1000ms, but it can take
slightly longer. 5000ms would cover most if not all cases.
Yes.
* Resolves [CASMINST-3544](https://connect.us.cray.com/jira/browse/CASMINST-3544)
* Change will also be needed in `main`
* Merge with https://github.com/Cray-HPE/csm-rpms/pull/139
_Are there known issues with these changes? Any other special considerations?_ …

CASMINST-3544 bios-baseline timeout

---

packages/cray-pre-install-toolkit/metal.packages

Changes since 1.11.1:
* CASMINST-3029 - NCN Automation Business Logic
* MTL-1569 add backwards compatibility for handoff bss-metadata command
* CASMINST-3598 generate ipam metadata key and push into bss

Release CSI 1.12.2

---

packages/cray-pre-install-toolkit/base.packages
packages/node-image-non-compute-common/base.packages

CANU has been updated to feature complete as of the 1.0.0 release and needs to be included in CSM 1.2 build.
* Resolves CASMNET-1059
* Merge with/before/after `https://github.com/Cray-HPE/csm-rpms/pull/150`
* `wasp`
* Tested upgrade from 0.0.5 and 0.0.6 to 1.0.0.
* On system testing of SHCD validate, configuration generation and validation and cabling checks.
- Were continuous integration tests run? **YES**
- Was upgrade tested? **YES**
- Was downgrade tested? **NO** as downgrade to 0.0.6 or lower will not be useful on CSM 1.2 systems.
None

CASMNET-1059: Bump CANU version to 1.0.0

---

packages/node-image-kubernetes/base.packages

This change adds support for HPE PDUs to the HSM ComponentEndpoints CT test.
* Resolves CASMTRIAGE-2801.
This change was tested by deploying the updated HSM ComponentEndpoints CT test to the system Hela which has HPE PDUs, executing the test, and verifying that the previously failing test cases began to pass.
Low risk.

CASMTRIAGE-2801 Add support for HPE PDUs to the HSM ComponentEndpoints CT test.

---

packages/node-image-kubernetes/base.packages
repos/cray.repos

-Add SAT RPM repository to repos/cray.repos
- Add prodmgr RPM to Kubernetes node image by adding it to base.packages
- Resolves [CRAYSAT-1241](https://connect.us.cray.com/jira/browse/CRAYSAT-1241)
Tested locally by building a Kubernetes NCN image.
- Local development environment
- Built a squashfs kubernetes image
- Mounted the resulting image and used chroot to check the RPM was installed and the command would run.
N/A
- [N/A] Version number(s) incremented, if applicable
- [N/A] Copyrights updated
- [N/A] License file intact
- [N/A] CHANGELOG.md updated
- [N/A] [HPC Product Announcement](https://cray.slack.com/archives/C026TVCSXLH) prepared, if applicable

CRAYSAT-1241: Add `prodmgr` RPM to CSM k8s image

---

packages/node-image-non-compute-common/base.packages
packages/node-image-non-compute-common/metal.packages

#167 moved SLE HPC into base.packages by mistake, this needs to go back to metal.packages.

Fix Ops from GCP Reorg Yesterday

---

packages/node-image-non-compute-common/base.packages

Add openssh packages of a specific version because the calculated requirement version conflicts with the installed packages during the build process of node-image-build.

CASMINST-2549: Add openssh packages to prevent dependency conflict

---

packages/node-image-non-compute-common/base.packages

CASMTRIAGE-2823: Add get_client_secret() function to check_no_wipe_flag.sh script
The kubectl command is not available/functioning on all storage nodes. The
check_no_wipe_ flag.sh script needs to execute the kubectl command to obtain the
Client Secret.
Added get_client_secret() function to check_no_wipe_ flag.sh script. If executing on any
storage node, locates an active functioning Kubernetes NCN node (master or worker) where
to execute the kubectl command to obtain the Client Secret.
Tested on hela (1.2.0-alpha.31).
CASMTRIAGE-2823
Tested on hela, 1.2.0-alpha.31 installed.
Was a fresh Install tested? N - N/A
Was an Upgrade tested? N - N/A
Was a Downgrade tested? N - N/A
If schema changes were part of this change, how were those handled in your upgrade/downgrade testing? N/A
Low
N/A

CASMTRIAGE-2823 main : TESTS: CSM validation metal.no-wipe check failing on storage nodes

---

packages/node-image-non-compute-common/base.packages

CASMTRIAGE-2823: Add get_client_secret() function to check_no_wipe_flag.sh script
The kubectl command is not available/functioning on all storage nodes. The
check_no_wipe_ flag.sh script needs to execute the kubectl command to obtain the
Client Secret.
Added get_client_secret() function to check_no_wipe_ flag.sh script. If executing on any
storage node, locates an active functioning Kubernetes NCN node (master or worker) where
to execute the kubectl command to obtain the Client Secret.
Tested on hela (1.2.0-alpha.31).
CASMTRIAGE-2823
Tested on hela, 1.2.0-alpha.31 installed.
Was a fresh Install tested? N - N/A
Was an Upgrade tested? N - N/A
Was a Downgrade tested? N - N/A
If schema changes were part of this change, how were those handled in your upgrade/downgrade testing? N/A
Low
N/A

CASMTRIAGE-2823 1.2 : TESTS: CSM validation metal.no-wipe check failing on storage nodes

---

packages/cray-pre-install-toolkit/base.packages

* Fixes bug where empty CHN network was created in SLS when chn inputs are not provided to CSI
* Fixes bug where CHN interface was being added to ipam parameters in basecamp
* Handles cabinets-yaml with empty string
* Checks for csm-version input to make sure 1.0 inputs are not used in 1.2 installs
* Resolves CASMTRIAGE-2702
* Resolves MTL-1568
* Resolves CASMINST-3410
* Resolves CASMNET-1061
* `drax`
Tested with various valid and invalid inputs to CSI on drax.  Checked the generated files to make sure they were correct.
No known issues

CSI update for: CASMTRIAGE-2702, MTL-1568, CASMINST-3410, and CASMNET-1061

---

packages/cray-pre-install-toolkit/base.packages

The metal-ipxe RPM ceased requiring dnsmasq as a dependency in CASMINST-2120 as a "slim-down" enhancement. This change reverts that, and restores the notion that metal-ipxe requires dnsmasq before install (as a dependency).
Yes.
* Resolves [CASMINST-3596](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3596)
* Change will also be needed in `main`
* Merge with 
_Are there known issues with these changes? Any other special considerations?_
No.

CASMINST-3596 metal-ipxe-2.0.11 requires dnsmasq

---

packages/compute-node.packages
packages/cray-pre-install-toolkit/base.packages
packages/node-image-non-compute-common/base.packages

Move craycli RPM version to 0.45.0 to pick up the CSM 1.2 (NERSC Phase 2) UAS content.
This change is backward compatible
* Resolves [CASMUSER-2812](https://jira-pro.its.hpecorp.net:8443/browse/CASMUSER-2812)
- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)? N/A
- Were continuous integration tests run? If not, why? N/A
- Was upgrade tested? If not, why? N/A
- Was downgrade tested? If not, why? N/A
- Were new tests (or test issues/Jiras) created for this change? N/A
No known issues or risks
- [ N/A ] Copyrights updated
- [ N/A ] Testing is appropriate and complete, if applicable
- [ N/A ] [HPC Product Announcement](https://cray.slack.com/archives/C026TVCSXLH) prepared, if applicable

Casmuser 2812

---

packages/cray-pre-install-toolkit/base.packages

The fix for CASMINST-2541 went a little too far when removing the api_gw_service aliases for HMN and removed the 10.94.100.71 reservation entirely. This reservation is still needed. This fix adds back that reservation but does it with no aliases.
See https://github.com/Cray-HPE/cray-site-init/pull/110 for more information.
* Resolves CASMINST-3701
This was tested on my laptop by building CSI locally and running csi config init on Hela's seed files. I did a comparison against what was generated with the main branch.
No known issues

CASMINST-3701:  CSI - Fix empty string generated for hmn_api_gw

---

packages/node-image-non-compute-common/base.packages

Added goss test and script to automate check for postgres pod backups (work done by Lindsay)
This is a new automation feature. It is a goss test that ensures that recent PostgreSQL pod backups exist for specific clusters.
Change a new feature, it is backwards compatible.
* Part of the 'Automation: Validate CSM Health (PET)' epic. CASM-2592
* CASMPET-4660 : Automate check for Postgres pod backups
* CASMPET-5145 : Add multiple tries to goss-k8s-postgres-replication-lag (this was merged to master a few weeks back and was just noted as missing from 1.2)
* wasp
* Hela
_How were the changes tested and success verified? If schema changes were part of this change, how were those handled in your upgrade/downgrade testing?_
- Were the …

CASMPET-4660 1.2 : Automate check for Postgres pod backups

---

packages/node-image-non-compute-common/base.packages

New goss-servers rpm to fix ca-cert test to allow for certs in different order, depending if they come from the file system or from metadata curl call.
* Resolves [CASMTRIAGE-2837](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-2837)
Tested fix on hela
* `hela`
```
ncn-m001:/opt/cray/tests/install/ncn/tests # goss -g /opt/cray/tests/install/ncn/tests/goss-platform-ca-certs-match-cloud-init-brad.yaml --vars=/opt/cray/tests/install/ncn/vars/variables-ncn.yaml v
.
Total Duration: 0.058s
Count: 1, Failed: 0, Skipped: 0
```
```
ncn-m002:~ # goss -g /opt/cray/tests/install/ncn/tests/goss-platform-ca-certs-match-cloud-init-brad.yaml --vars=/opt/cray/tests/install/ncn/vars/variables-ncn.yaml v
.
Total Duration: 0.059s
Count: 1, Failed: 0, Skipped: 0
```
Low

New goss-servers rpm to fix ca-cert test

---

packages/cray-pre-install-toolkit/metal.packages
packages/node-image-non-compute-common/metal.packages

Hexane should be yanked out of 1.2, it was brought in recently as a curiosity but it could enable nefarious/wrong-doings on a system. The nature of the program pertains to TPM/SecureBoot, and can prevent a server from booting when used incorrectly.
Yes.

MTL-1598 Remove hexane until actually desired, if at all

---

packages/node-image-kubernetes/base.packages

This updates the version of the `prodmgr` RPM to a newer version that includes a man page.
* Resolves CRAYSAT-1246
* `lemondrop`
* I built the image locally using `packer`
* I installed the RPM on lemondrop and ran the command.
N/A
- [N/A] Version number(s) incremented, if applicable
- [N/A] Copyrights updated
- [N/A] License file intact
- [Y] Target branch correct
- [N/A] CHANGELOG.md updated
- [Y] Testing is appropriate and complete, if applicable
- [N/A] [HPC Product Announcement](https://cray.slack.com/archives/C026TVCSXLH) prepared, if applicable

CRAYSAT-1246: update prodmgr rpm

---

packages/node-image-kubernetes/base.packages

This change updates the path to the hms-pytest image in Nexus since images are no longer being uploaded to the old location.
* Resolves CASMHMS-5312.
This change was tested on Mug running csm-1.2.0-alpha.43 by pulling the hms-pytest image from the new location and verifying that the previously failing CT tests began to pass. Also verified with Zach C. that the new path is correct and that the previous location is no longer supported.
Low risk that fixes an out-of-date image path.

CASMHMS-5312 Update hms-pytest image location for Nexus csm-1.2

---

packages/node-image-kubernetes/base.packages

This change updates the path to the hms-pytest image in Nexus since images are no longer being uploaded to the old location.
* Resolves CASMHMS-5312.
This change was tested on Mug running csm-1.2.0-alpha.43 by pulling the hms-pytest image from the new location and verifying that the previously failing CT tests began to pass. Also verified with Zach C. that the new path is correct and that the previous location is no longer supported.
Low risk that fixes an out-of-date image path.

CASMHMS-5312 Update hms-pytest image location for Nexus main

---

packages/node-image-non-compute-common/base.packages

New version of goss-servers to fix goss test to remove blank lines from file system cert before comparing to the one in metadata
* Resolves [CASMINST-3796](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3796)
Tested this in place on mug:
```
ncn-m002:~ # export GOSS_BASE=/opt/cray/tests/install/ncn; goss -g /opt/cray/tests/install/ncn/tests/goss-platform-ca-certs-match-cloud-init.yaml --vars=/opt/cray/tests/install/ncn/vars/variables-ncn.yaml validate
.
Total Duration: 0.061s
Count: 1, Failed: 0, Skipped: 0
```
* `mug`
Tested in place.
Low

New version of csm-testing

---

packages/node-image-non-compute-common/base.packages

Allow the livecd bios baseline test more time to run the underlying script (timing out with 5 seconds).
* Resolves [CASMINST-3696](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3696)
Ran on surtur
* `surtur`
Ran on surtur -- got past the timeout.  I couldn't figure out how to set the ipmi creds properly, but that's probably me.
Low

New version of goss-servers

---

packages/cray-pre-install-toolkit/base.packages
packages/node-image-non-compute-common/base.packages

This change removes a duplicated code block from verify_hsm_discovery.py which stops it from running and printing the checks for CabinetPDUControllers twice instead of once. The extra output was causing confusion during installs while troubleshooting discovery failures.
* Resolves CASMHMS-5310.
This change was tested on Mug running csm-1.2.0-alpha.43 by copying the new version of the script onto the NCN, running it, and verifying that the duplicated output from the original script was no longer present in the updated version.
Previous (two identical "CabinetPDUControllers" entries per cabinet):
```
<snip>
River Cabinet Checks
====================
x3000
Nodes: PASS
NodeBMCs: WARNING
- x3000c0s1b0 - Not found in HSM Components; No mgmt port connection; BMC of mgmt node ncn-m001.
RouterBMCs: …
```

CASMHMS-5310 Remove duplicate CabinetPDUController output from verify_hsm_discovery csm-1.2

---

packages/cray-pre-install-toolkit/base.packages
packages/node-image-non-compute-common/base.packages

This change removes a duplicated code block from verify_hsm_discovery.py which stops it from running and printing the checks for CabinetPDUControllers twice instead of once. The extra output was causing confusion during installs while troubleshooting discovery failures.
* Resolves CASMHMS-5310.
This change was tested on Mug running csm-1.2.0-alpha.43 by copying the new version of the script onto the NCN, running it, and verifying that the duplicated output from the original script was no longer present in the updated version.
Previous (two identical "CabinetPDUControllers" entries per cabinet):
```
<snip>
River Cabinet Checks
====================
x3000
Nodes: PASS
NodeBMCs: WARNING
- x3000c0s1b0 - Not found in HSM Components; No mgmt port connection; BMC of mgmt node ncn-m001.
RouterBMCs: …
```

CASMHMS-5310 Remove duplicate CabinetPDUController output from verify_hsm_discovery

---

packages/cray-pre-install-toolkit/base.packages
packages/node-image-non-compute-common/base.packages

Canu version bump
- Adds canu testing feature
- Fixed canu validate BGP for csm 1.2
CASMINST-3485
Drax, Hela, vritualEnv
successfully ran CANU on the systems above.

1.2 casminst-3485

---

packages/node-image-kubernetes/base.packages
packages/node-image-non-compute-common/base.packages

Also pulls in fix for CASMINST-3485

CASMINST-3859: Move cfs-state-reporter check from cmsdev tool into goss NCN healthcheck suite

---

packages/cray-pre-install-toolkit/base.packages

When copying the node images csi does not verify the existence of the target directory resulting in a somewhat confusing error message should it not exist.
* Resolves [CASMINST-3866](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3866)
* `hela`
Old behaviour
```
ncn-m001:~ # csi pit populate pitdata "${CSM_RELEASE}/images/kubernetes/" /mnt/pitdata/data/k8s/ -kiK
5.3.18-59.34-default-0.2.43.kernel----------------> /mnt/pitdata/data/k8s/...Failed "open /mnt/pitdata/data/k8s/5.3.18-59.34-default-0.2.43.kernel: no such file or directory"
initrd.img-0.2.43.xz------------------------------> /mnt/pitdata/data/k8s/...Failed "open /mnt/pitdata/data/k8s/initrd.img-0.2.43.xz: no such file or directory"
kubernetes-0.2.43.squashfs------------------------> …
```

CASMINST-3866 - Check target directory exists before attempting to copy image artifacts

---

packages/cray-pre-install-toolkit/base.packages
packages/node-image-non-compute-common/base.packages

- Changes `git` to `git-core` to limit the number of packages installed
- Specifies `openssh` version to prevent conflicts during general package installation
- Adds `parted` to enable partition resizing for building of cloud images

VSHA-300: Update packages for LiveCD Build

---

packages/cray-pre-install-toolkit/base.packages

Regenerate the the BSS host_records metadata using data from SLS during CSM 1.2 upgrade
https://github.com/Cray-HPE/cray-site-init/pull/117
* Resolves CASMINST-3831
For Testing see: https://github.com/Cray-HPE/cray-site-init/pull/117
Requires additional end to end testing on Baremetal during a CSM 1.2 upgrade. But all of the changes made to a system are contained within the Global boot parameters …

(CSM 1.2) CASMINST-3831 bump CSI version

---

packages/cray-pre-install-toolkit/base.packages

Regenerate the the BSS host_records metadata using data from SLS during CSM 1.2 upgrade
https://github.com/Cray-HPE/cray-site-init/pull/117
* Resolves CASMINST-3831
For Testing see: https://github.com/Cray-HPE/cray-site-init/pull/117
Requires additional end to end testing on Baremetal during a CSM 1.2 upgrade. But all of the changes made to a system are contained within the Global boot parameters …

(main) CASMINST-3831: Bump csi version

---

packages/compute-node.packages
packages/extra.packages
packages/node-image-non-compute-common/cms.packages

This mod changes the population behavior for cfs-trust; this migrates
the behavior over to a patch operation in order to be a good citizen for
any service that ends up populating information afterwards. Normally, we
don't re-PUT once our key is there, and since our services is one of the
first to push content into the bss metadata service, there is no
problem.
However, during an upgrade or scenarios where cfs-trust metadata goes
missing, subsequent PUT operations zero any incidental keys stored in
BSS metadata global section; this information then needs to be recovered
(sometimes manually).
Finally, this mod updates the behavior of cfs-trust and changes it to
re-populate our missing key if it ever goes missing for whatever reason.
Previously, a pod restart would accomplish this similar …

CASMCMS-7783 Manifest Update

---

packages/node-image-kubernetes/base.packages

This change updates the HSM CT tests to allow custom component roles and subroles. Previously these were expected to be one of the pre-defined roles but now we've added support and documentation for setting custom roles. Sites using custom roles or subroles (as seen on Pawsey, for example) will encounter HMS validation test failures without this update.
* Resolves [CASMHMS-5365](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5365).
This change was tested on Mug by deploying the updated tests, executing them after setting a custom node SubRole in HSM, and verifying that the previously failing test cases began to pass.
Very low risk, great benefit to stop false test failures from being reported.

CASMHMS-5365 Update HSM CT tests for custom component roles and subroles.

---

packages/cray-pre-install-toolkit/base.packages
packages/node-image-non-compute-common/base.packages

Update package version for hpe-csm-scripts for CASMHMS-5346 - Change lock_management_nodes.py to lock nodeBMCs of management nodes
* Resolves [CASMHMS-5346](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5346)
For testing, see https://github.com/Cray-HPE/hpe-csm-scripts/pull/9
low

Update package version for hpe-csm-scripts

---

packages/cray-pre-install-toolkit/base.packages

Changed default BGP CMN ASN to 65532, and BGP NMN ASN to 65531. The CMN ASN was perviously set to a value that was reserved for documentation usage.
https://github.com/Cray-HPE/cray-site-init/pull/120
backwards compatible
* Resolves [CASMINST-3804](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3804)
For testing see: https://github.com/Cray-HPE/cray-site-init/pull/120
_Are there known …

    CASMINST-3804: Update cray-site-init RPM to 1.14.9.

---

packages/cray-pre-install-toolkit/base.packages

Changed default BGP CMN ASN to 65532, and BGP NMN ASN to 65531. The CMN ASN was perviously set to a value that was reserved for documentation usage.
https://github.com/Cray-HPE/cray-site-init/pull/120
backwards compatible
* Resolves [CASMINST-3804](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3804)
For testing see: https://github.com/Cray-HPE/cray-site-init/pull/120
_Are there known …

CASMINST-3804: Update cray-site-init RPM to 1.14.9.

---

packages/node-image-kubernetes/base.packages
repos/cray.repos

This change removes references to car.dev.cray.com. This change also upgrades the version of `cray-sdu-rda` as the version is no longer available in new repositories.
* Resolves [CASMINST-3984](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3984)
Tested in `node-image-build` build pipeline.

CASMINST-3984: Remove car.dev.cray.com references

---

packages/cray-pre-install-toolkit/base.packages
packages/node-image-non-compute-common/base.packages

Update polkit packages on PIT and NCN nodes to version `0.116-3.6.1`. This version is available for SLES 15 SP2 distros through LTSS repos (original SLES 15 SP2 ISO comes with `0.116-3.3.1`). According to https://www.suse.com/de-de/security/cve/CVE-2021-4034.html, this version contains a fix for CVE-2021-4034.
* Resolves [MTL-1604](https://jira-pro.its.hpecorp.net:8443/browse/MTL-1604)
Ran image builds to verify:
https://jenkins.algol60.net/job/Cray-HPE/job/cray-pre-install-toolkit/job/release%252Fcsm-1.0/6/consoleFull
[ DEBUG   ]: 21:18:44 | (217/227) Installing: libpolkit0-0.116-3.6.1.x86_64 [........done]
[ DEBUG   ]: 21:19:13 | (218/227) Installing: kernel-source-5.3.18-24.99.1.noarch [..................done]
[ DEBUG   ]: 21:19:14 | (219/227) Installing: …

MTL-1604: CVE-2021-4034: pwnkit: Local Privilege Escalation in polkit's pkexec [release/1.0]

---

scripts/rpm-functions.sh

Ensure `set +e` is set for rpm installs.  Some callers of this function execute in an environment where certain commands or capabilities may not be present.  For example, the LiveCD build, which uses these csm-rpms functions from within a script that has `set -e`.  It is common for rpm scripts to encounter errors.  These should not halt the execution of the calling script.

Allow errors in rpm scriptlets

---

packages/node-image-non-compute-common/base.packages

This adds tests that are run on workers and storage nodes after the nodes have been deployed in fresh install (csi pit validate --ceph and csi pit validate --k8s) and after they are upgraded.
* Resolves CASMINST-4001
* Related to CASMINST-3828
* `fanta`
Ran `csi pit validate --ceph` and `csi pit validate --k8s` to test fresh install
Ran `ncn-upgrade-tests-storage.yaml` and `ncn-upgrade-tests-storage.yaml` to test upgrades.
Verified that the new test shows up in the output and passes.

CASMINST-4001: Update goss-server package to 1.11.0

---

packages/node-image-storage-ceph/base.packages

Add kubernetes python module to storage nodes so bican scripting can talk to sls for bican toggle and network configs.
* Resolves [CASMNET-1154](https://jira-pro.its.hpecorp.net:8443/browse/CASMNET-1154)
A bit on wasp -- looks like that's the only missing module, but installing the rpm directly w/out all the repos pulls in too many dependencies.
* `wasp`
Stopped short of installing the whole dependency chain
Low

Add k8s python module to storage nodes for bican route script

---

packages/node-image-non-compute-common/base.packages

Remediation steps for velero backup test don't permanently delete a backup, need to use velero command instead (not kubectl).
* Resolves [CASMINST-4059](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4059)
Ran the velero delete on surtur, the backup did not come back.
* `surtur`
Manually ran the new remediation step and it worked.
None/Low

Change velero backup test remediation to really delete PartiallyFailed backups

---

packages/cray-pre-install-toolkit/base.packages

This adds the capability to specify edge routers in switch_metadata.csv to get them added to SLS with xnames and get them added as CHN peers to the metallb config map.
See https://github.com/Cray-HPE/cray-site-init/pull/121
* Resolves CASMNET-1157
I have tested this by running `csi config init` with hela seed files using various combinations of inputs.
* With two edge switches specified and bgp-peer-types set to [spine, edge]
* Without edge switches specified in switch_metadata.csv
* With two edge switches specified but bgp-peer-types set to [spine]
* With no edge switches specified but bgp-peer-types set to [spine, edge]
* With only one edge switch specified
* With and without CHN defined in CSI inputs
- [N/A] Version number(s) incremented, if applicable
- [N/A] [HPC Product …

CASMNET-1157: Update cray-site-init RPM to 1.16.0

---

repos/hpe.template.repos

This will need to be revised once the upstream repodata for `current` is repaired.  See also the previous merge to this branch.

Use previous version only

---

packages/cray-pre-install-toolkit/base.packages

This set of changes fixes both CASMINST-4089 and CASMNET-1173
CASMINST-4089 - A valid configuration can have either CAN, CHN, or both. This fixes the case where setting the host records with either CAN or CHN are not specified caused a failure. I also added unit tests for the use cases of: only CAN is defined, only CHN is defined, neither CAN nor CHN are defined. The last case is expected to cause a failure and the unit test checks for that.
CASMNET-1173 - The prefix-length for CAN and CMN interaces in the ipam settings of BSS should come from the CAN/CMN supernet and not from the bootstrap subnet. This fixes those settings. It also fixed the unit tests to ensure that they are set appropriately. This was not caught previously in unit tests because the SLS test data was not as it would be …

Casminst 4089 casmnet 1173

---

packages/cray-pre-install-toolkit/base.packages

- Fixes #CASMINST-4116
The HPE master and storage nodes have two NICs with two ports each.  In 1.0, these devices were named mgmt0, mgmt1, mgmt2, and mgmt3 and we would specify on the kernel cmdline which of those two devices made up bond0.  In 1.2, the device naming has changes to mgmt0, mgmt1, sun0, and sun1 and we presume that bond0 is always mgmt0 and mgmt1.   However the device that is named mgmt1 is different in 1.2 than it was in 1.0.   Because of all of this we need to make sure that `csi upgrade metadata` changes the ifnames to be what is expected for 1.2.    Master and storage nodes with only 1 NIC (on GB and Intel) can be left as they are.
I added several unit tests to check both 1 NIC and 2 NIC cases for Master and Storage as well as for the Worker nodes. …

CASMINST-4116: Update cray-site-init RPM to 1.16.2

---

packages/node-image-non-compute-common/base.packages

Pull in:
* Move interface MAC check into script file
* CASMINST-4157: Increase some test timeouts to avoid false failures
* Appease the license checker
* Remove needless comment from livecd preflight script
* Replace hard-coded paths with GOSS_BASE variable; protect string variables with quotes
* Make script hash-bang lines consistent
* Correct grep command regular expressions
* CASMINST-4157: Remove unnecessary -it arguments to kubectl exec commands in scripts

Update csm-testing/goss-servers to v1.6.51

---

packages/node-image-non-compute-common/base.packages

Pull in:
* CASMINST-4223: Enable logging for bmc-check, podman-basecamp, podmap-nexus
* CASMINST-4224: Move tests to scripts and enable logging for bond-members-have-correct-mtu, switch-bgp-neighbor-aruba-or-mellanox

Update csm-testing/goss-servers to v1.12.15

---

packages/node-image-non-compute-common/base.packages

This adds the goss-switch-bgp-neighbor-aruba-or-mellanox.yaml test to ncn-upgrade-preflight-tests.yaml suite.  This allows us to check the BGP peering sessions before we attempt to boot nodes.
* Resolves CASMINST-4265
* `drax`
I manually added this test to the ncn-upgrade-preflight-tests.yaml suite and ran the suite as it is done in prerequisites.sh.   I verified that the test ran and checked the logs for the test in /opt/cray/tests/install/logs/bgp_neighbors_established.
```
GOSS_BASE=/opt/cray/tests/install/ncn goss -g /opt/cray/tests/install/ncn/suites/ncn-upgrade-preflight-tests.yaml --vars=/opt/cray/tests/install/ncn/vars/variables-ncn.yaml validate
```

CASMINST-4265: Bump goss-servers to 1.12.19

---

packages/node-image-non-compute-common/base.packages

A change was put in to add `set -e` to the top of the livecd-preflight-check script.  When `/usr/bin/goss validate -f json` is run in that script to execute all of the goss tests in that suite, it will return non-zero if any of the tests fail.  The `set -e` causes the script to then stop execution immediately without giving any output indicating which tests failed.   We need to run `/usr/bin/goss validate -f json` without the `set -e`.
* Resolves CASMINST-4142
* `drax`
I ran `/opt/cray/tests/install/livecd/automated/livecd-preflight-checks` on drax with this fix and injected a test failure I was able to see the test results include the one test that was failing.

CASMINST-4142: Update goss-servers to v1.6.53

---

packages/cray-pre-install-toolkit/base.packages

Cray Site Init generated CHN reservations with xname rather than common name. This created two xname records in DNS and played havoc with SAT and DVS.  Additionally UANs were missing from the CHN.  This change remediates these two issues for new/fresh installs of CSM 1.2 where the system has a CHN.
* Resolves CASMINST-4372
* Hela data (has a CHN)
* Surtur data (does not have a CHN)
Ensured common names were generated in CHN SLS reservations and that UAN entries were generated in the CHN SLS structured.
None

CASMINST-4372 CSI fix for CHN reservations

---

packages/cray-pre-install-toolkit/base.packages

Cray Site Init generated CHN reservations with xname rather than common name. This created two xname records in DNS and played havoc with SAT and DVS.  Additionally UANs were missing from the CHN.  This change remediates these two issues for new/fresh installs of CSM 1.2 where the system has a CHN.
* Resolves CASMINST-4372
* Hela data (has a CHN)
* Surtur data (does not have a CHN)
Ensured common names were generated in CHN SLS reservations and that UAN entries were generated in the CHN SLS structured.
None

CASMINST-4372 CSI fix for CHN reservations (main)

---

build/list-files.sh
repos/cray-compute.repos
scripts/rpm-functions.sh

The repos at `car.dev.cray.com` are being removed. This PR removes references to those repos and the functions that installed those repos.
* Resolves [CASMINST-3985](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3985)
Built `node-image-build` NCN images locally.
Risk that the cray-compute functions are needed for other work.

CASMINST-3985: Remove defunct repositories and references

---

scripts/update-package-versions.sh

A specific compute repos file no longer exists. This removes a call to a non-existent file.
* Resolves [CASMINST-3985](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3985)
- Built `node-image-build` locally.

CASMINST-3985 - Adjust package upgrades to no longer rely on removed repos.

---

packages/cray-pre-install-toolkit/base.packages

We need prevent UAIs from getting to CMN like we do with NMNLB.   The way this is being accomplished with NMNLB is that a route exists on the UAI that goes to a gateway that it cannot get to.   We are doing the same thing for CMN by adding the CMN subnet to macvlan routes defined in customizations.yaml.  This causes it to be added to the relevant network attachment definitions.
- Fixes #CASMINST-4283
I did a local build of CSI.  I ran "csi config init" with the resulting binary using the seed files from hela.   I verified that the correct CMN route (10.103.0.0./25) was added to the customizations.yaml generated by CSI.
```
macvlansetup:
nmn_subnet: 10.252.2.0/23
nmn_supernet: 10.252.0.0/17
nmn_supernet_gateway: 10.252.0.1
nmn_vlan: bond0.nmn0
nmn_reservation_start: 10.252.2.10 …
```

CASMINST-4283:  Bump CSI version to 1.16.11

---

repos/cos.repos
repos/cray.repos
scripts/rpm-functions.sh

The COS repos were causing problems for PIT ISO builds due to
conflicting compute-node kernel RPMs in those COS repos.  Split
out COS repos into their own file and add a `--pit` option to
`setup-packages-repos` to allow skipping COS repos for PIT builds.

Move COS repos out of cray.repos

---

packages/cray-pre-install-toolkit/base.packages
packages/node-image-non-compute-common/base.packages

- Feature:  LAG preserve to help in adopting CANU
- Feature:  Send arbitrary read-only commands to switches.
- Many switch configuration template fixes.
- Many docs updates and changes.
[Release Notes](https://github.com/Cray-HPE/canu/releases/1.5.6)
* Resolves CASMNET-1518
These changes have soaked in development and been used on multiple internal systems for up to several weeks.
* Nox testing
* Gamora, Jolt1, Wasp and a large customer environment

CASMNET-1518: CANU Release 1.5.6 (1.2)

---

packages/node-image-non-compute-common/base.packages

Install binary on NCNs to support hierarchical namespace management via `kubectl hns *` commands.  This feature is targeted towards post-1.3, however we don't want to require an NCN image for this feature.  Installing the binary in 1.3 NCN images will be benign.
* Resolves [CASMINST-4297](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4297)
```
ncn-m003-eef2744f:~ # kubectl hns tree tenants
Error: unknown command "hns" for "kubectl"
Run 'kubectl --help' for usage.
```
```
ncn-m003-eef2744f:~ # rpm -Uvh https://artifactory.algol60.net/artifactory/csm-rpms/hpe/stable/sle-15sp2/cray-kubectl-hns-plugin/x86_64/cray-kubectl-hns-plugin-1.0.0-1.x86_64.rpm
Retrieving https://artifactory.algol60.net/artifactory/csm-rpms/hpe/stable/sle-15sp2/cray-kubectl-hns-plugin/x86_64/cray-kubectl-hns-plug …
```

Add kubectl hns plugin for CSM 1.3

---

packages/compute-node.packages
packages/cray-pre-install-toolkit/base.packages
packages/node-image-non-compute-common/base.packages

This change adds support for the 'GET' operation to the HSM /v2/locks/status API which will list the lock status of all components in HSM. Optional query parameters may be supplied to filter the results based on component Type, State, Role, SubRole, and Locked, Reserved, ReservationDisabled status. Several corrections to the HSM Swagger specification and a few minor CT test updates are also included.
* Resolves CASMHMS-4974.
This change was tested by:
- Implementing unit tests for the new /v2/locks/status 'GET' operation
- Spinning up a local instance of HSM in a docker-compose environment, manually populating it with components and setting locks, and executing calls with various query parameters specified
- Upgrading the running HSM service on Mug using Helm to deploy the new version and …

CASMHMS-4974 Add support for HSM /v2/locks/status 'GET' operation for listing all locks

---

packages/cray-pre-install-toolkit/base.packages

Includes further updates for podman dependent packages such as pit-nexus and metal-basecamp to work with podman3.

Podman updates / reattempt

---

packages/node-image-non-compute-common/base.packages

Add service restart for patroni service in lagging members before validating lag (required when bouncing masters due to backoff in postgres pods that's not tunable), as well as correct lag check to exec into the leader.
* Resolves [CASMINST-4544](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4544)
Ran many times on surter when rebuilding master node.
* `surtur`
Ran many times
Low

Add patroni service restarts for lagging PG members before checking lag

---

packages/cray-pre-install-toolkit/base.packages

- Fixes #CASMTRIAGE-3253
Renames the uai_macvlan_bridge reservation in the uai_macvlan subnet to uai_nmn_blackhole.   uai_macvlan_bridge is no longer being used.  We are repurposing that reservation to be used as the gw for the NMNLB route in UAIs.  This will block access to the NMNLB from the UAI.
While in the same same section of code, I also made the allocation of IPs to the uai_macvlan reservations consistent.  This solves the issue with running CSI multiple times and ending up with different IPs for these reservations.
Built CSI locally and ran the `csi config init` with seed files from hela.   Checked the generated sls_input_file.json and customizations.yaml.

CASMTRIAGE-3253:  Bump CSI version to 1.16.16

---

packages/cray-pre-install-toolkit/base.packages

- Fixes #CASMTRIAGE-3253
Renames the uai_macvlan_bridge reservation in the uai_macvlan subnet to uai_nmn_blackhole.   uai_macvlan_bridge is no longer being used.  We are repurposing that reservation to be used as the gw for the NMNLB route in UAIs.  This will block access to the NMNLB from the UAI.
While in the same same section of code, I also made the allocation of IPs to the uai_macvlan reservations consistent.  This solves the issue with running CSI multiple times and ending up with different IPs for these reservations.
Built CSI locally and ran the `csi config init` with seed files from hela.   Checked the generated sls_input_file.json and customizations.yaml.

CASMTRIAGE-3253: Bump CSI version to 1.17.1

---

packages/cray-pre-install-toolkit/base.packages

- Fixes MTL-1710
This fixes the following errors if `pit-init` is invoked on a fresh install where `data.json` does not exist yet.
```bash
= PIT Identification = COPY/CUT END =========================================
Setting up NTP ...
cat: /var/www/ephemeral/configs/data.json: No such file or directory
cat: /var/www/ephemeral/configs/data.json: No such file or directory
cat: /var/www/ephemeral/configs/data.json: No such file or directory
cat: /var/www/ephemeral/configs/data.json: No such file or directory
cat: /var/www/ephemeral/configs/data.json: No such file or directory 
```
The change moves the `configure-ntp` call after `data.json` is copied into place.
What is less risky, or more risky now - or if your mod fails is there a new risk?
This is less risky since it …

MTL-1710 Fix freshinstall issue with configure-ntp

---

packages/cray-pre-install-toolkit/base.packages

- Fixes MTL-1710
This fixes the following errors if `pit-init` is invoked on a fresh install where `data.json` does not exist yet.
```bash
= PIT Identification = COPY/CUT END =========================================
Setting up NTP ...
cat: /var/www/ephemeral/configs/data.json: No such file or directory
cat: /var/www/ephemeral/configs/data.json: No such file or directory
cat: /var/www/ephemeral/configs/data.json: No such file or directory
cat: /var/www/ephemeral/configs/data.json: No such file or directory
cat: /var/www/ephemeral/configs/data.json: No such file or directory 
```
The change moves the `configure-ntp` call after `data.json` is copied into place.
What is less risky, or more risky now - or if your mod fails is there a new risk?
This is less risky since it …

MTL-1710 New pit-init with fixed call to configure-ntp

---

packages/cray-pre-install-toolkit/base.packages

- In order to have interoperability between the HMN-SHCD parser and CANU we need to be able to have 0 as a destination port number on the HMN tab of the SHCD.
- This change allows SLS to accept 0 as a port number.  This is the same behavior as leaving it blank.
- Fixes # CASMINST-4549
Tested locally.  All tests passed.
Generated SLS file has no differences with a "" or "0" as port destination.

CASMINST-4549 main

---

packages/cray-pre-install-toolkit/base.packages

- In order to have interoperability between the HMN-SHCD parser and CANU we need to be able to have 0 as a destination port number on the HMN tab of the SHCD.
- This change allows SLS to accept 0 as a port number.  This is the same behavior as leaving it blank.
- Fixes # CASMINST-4549
Tested locally.  All tests passed.
Generated SLS file has no differences with a "" or "0" as port destination.

CASMINST-4549 1.2

---

packages/node-image-non-compute-common/base.packages

[CASMINST-4565](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4565) Enhance kube-system Goss test to remove need for manual test during Deploy Management Nodes install procedure.
[CASMINST-4576](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4576) Validate that ceph -s works where and when it ought to. This would have caught a problem on the gamora install much earlier and saved hours of time.
See source PRs for full details:
https://github.com/Cray-HPE/csm-testing/pull/301
https://github.com/Cray-HPE/csm-testing/pull/304

CASMINST-4565/CASMINST-4576: Goss test improvements

---

.github/workflows/shellcheck.yml
build/create-index.sh
build/update-packages.sh
scripts/rpm-functions.sh
scripts/update-package-versions.sh

- Partially implements MTL-1497
This adds a shellcheck Action.  It's set to fail on warnings or errors.  As a starting point, I disabled the existing warnings and any future scripts will need to pass this gate.
Adds shellcheck workflow to this repo.
N/A
Low

MTL-1497 add shellcheck

---

packages/cray-pre-install-toolkit/metal.packages

SLE_HPC-release is handled in a provisioner for pit-common. The node-image-build repo handles this RPM differently than
cray-pre-install-toolkit, and having this here actually breaks the zypper command due to a conflict.
cray-pre-install-toolkit already has this package specified in its config.xml file, it doesn't need to have it in csm-rpms.
Removing this will maintain the HPC integrity while enabling MTL-1476 builds.

MTL-1476 Fix Builds

---

packages/node-image-non-compute-common/base.packages

Adds more logic around checking if a leader exists.
* Resolves [CASMINST-4683](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4683)
* Change will also be needed in master and release/csm-1.2
drax and vshasta
o Verified in vshasta where a cluster had no leader (no patroni services were running on any members)
```
$ ./postgres_replication_lag.sh -p
PostgreSQL cluster checks may take several minutes, depending on the number of attempts per cluster.
Checking to see if any cluster members need a patroni …
```

CASMINST-4683 main : worker node upgrade failed - cray-console-data-postgres

---

packages/node-image-non-compute-common/base.packages

Adds more logic around checking if a leader exists.
* Resolves [CASMINST-4683](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4683)
* Change will also be needed in master and release/csm-1.2
drax and vshasta
o Verified in vshasta where a cluster had no leader (no patroni services were running on any members)
```
$ ./postgres_replication_lag.sh -p
PostgreSQL cluster checks may take several minutes, depending on the number of attempts per cluster.
Checking to see if any cluster members need a patroni …
```

CASMINST-4683 1.2 : worker node upgrade failed - cray-console-data-postgres

---

packages/cray-pre-install-toolkit/base.packages

Pulls in:
- CASMINST-4745: bios-baseline fix for default prompt (https://github.com/Cray-HPE/pit-init/pull/38)
- MTL-1787: pit-init reorg (https://github.com/Cray-HPE/pit-init/pull/39)

CASMINST-4745 MTL-1787

---

packages/cray-pre-install-toolkit/base.packages
packages/node-image-non-compute-common/base.packages

Upgrading Canu from 1.5.7 to 1.6.1.
Disable load balacing configuration for Dell CDU/Leaf.
Add canu report network version feature.
Fix Errors in the output of canu test
Add route-map and prefixes to allow connection to UAI's from CAN network.
Fix Dell4148 template to include correct port count
https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-3322
https://jira-pro.its.hpecorp.net:8443/browse/CASMNET-1572
Nox, surtur, drax

canu release 1.6.1 (main)

---

packages/cray-pre-install-toolkit/base.packages
packages/node-image-non-compute-common/base.packages

Upgrading Canu from 1.5.7 to 1.6.1.
Disable load balacing configuration for Dell CDU/Leaf.
Add canu report network version feature.
Fix Errors in the output of canu test
Add route-map and prefixes to allow connection to UAI's from CAN network.
Fix Dell4148 template to include correct port count
https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-3322
https://jira-pro.its.hpecorp.net:8443/browse/CASMNET-1572
Nox, surtur, drax

canu release 1.6.1 (rel/1.2)

---

repos/suse.template.repos

This is a followup PR to #435 that uses the new algol60 repos.

CASMINST-4770 Use algol60 mirrors

---

Jenkinsfile.github
packages/node-image-non-compute-common/google.packages

These packages were installed manually in the node-images:google images, this PR moves them from node-images to csm-rpms.
This was supposed to be cleaned up in the original #437 PR but was missed.

MTL-1790 Add vshasta packages

---

packages/node-image-non-compute-common/base.packages

Update goss-servers to pull in CASMINST-4720, which adds test logging to a handful of Goss tests. See source PR for details:
https://github.com/Cray-HPE/csm-testing/pull/328
This is only going into 1.3.

CASMINST-4720: Add logging to additional Goss tests

---

packages/node-image-non-compute-common/base.packages

This is a corner case that is being addressed in 1.3
Once the etcd cluster is created, it can take up to hour for the etcd backup crd to get created.
Once the etcd backup crd is created, the etcd backup occur every 24 hours
Thus it can actually take 25 hours after the cluster is created for the backup to exist.
_Is this change backwards incompatible, backwards compatible, or a backwards compatible bugfix?_ Yes
* Resolves [CASMTRIAGE-3386](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-3386)
* Change will also be needed in NA
Tested on drax
* Local …

CASMTRIAGE-3386-1.3 : TESTS: CSM etcd cluster backups silently failing

---

packages/cray-pre-install-toolkit/base.packages
packages/node-image-non-compute-common/base.packages

[1.6.4]
Documentation updates to docs/network_configuration_and_upgrade
[1.6.3]
Use full show run commands to retrieve running config from canu network backup
UAN CAN ports are now shutdown if CHN is enabled.
Mellanox UAN CAN ports now only allow the CAN vlan.
Added CMC subrack port configuration.
Documentation updates to docs/network_configuration_and_upgrade
[1.6.2]
Correct the 'slot warning' to specify more accurate options
[_List and characterize relationship to Jira/Github issues and other pull requests. Be sure to list dependencies._
* Resolves [CASMNET-1591](https://jira-pro.its.hpecorp.net:8443/browse/CASMNET-1591)
Nox

canu 1.6.4 release

---

packages/node-image-kubernetes/base.packages

PR #416 did not correctly update the sdu-rda package, the package did end up getting into an NCN image but it appears broken when csm-rpms update scripts run.
This PR simply corrects the previous PR and ensures that cray-sdu-rda is defined properly.

HPCCHT3-3210 redo

---

packages/cray-pre-install-toolkit/base.packages

This removes the ad-hoc install of kubectl by leveraging CSM-RPMs. CSM-RPMs now has kubectl listed from the completion of [MTL-1790](https://connect.us.cray.com/jira/browse/MTL-1790).
This also brings kubectl up to the matching version that is used in the NCN images.

MTL-1796 Add kubectl to LiveCD base packages

---

repos/suse.template.repos

libfmt7 was coming from SLES repos, but no more updates will be made to
those repos from SLES. This ensures that the openSUSE Backports standard
repo is available for upcoming libfmt7 updates.
libfmt7 is the same version at this present time between the two repos.

MTL-1797 Add Missing libfmt7 repo

---

packages/cray-pre-install-toolkit/base.packages
packages/node-image-kubernetes/base.packages
packages/node-image-non-compute-common/base.packages
repos/cray.repos

- There's a new craycli (0.53.0-1).
- Pulls loftsman from algol60 using a stable/release tag instead of a development version from arti.dev.cray.com
- Pulls manifestgen with a stable RPM name instead of "development" in the name (RPM name was fixed in https://artifactory.algol60.net/artifactory/csm-rpms/hpe/stable/sle-15sp2/manifestgen/x86_64/manifestgen-v1.3.6-1.x86_64.rpm)

CASMCMS-7876 Update to craycli 0.53.0-1 and pull loftsman/manifestgen from algol60

---

packages/cray-pre-install-toolkit/base.packages

See description in csi PR for what was changed:
https://github.com/Cray-HPE/cray-site-init/pull/192/files
New routes for HMN and HMNLB are added to the net-attach-def to blackhole the traffic from a UAI.
* Resolves CASMUSER-3028
* Merge after
https://github.com/Cray-HPE/docs-csm/pull/1901
https://github.com/Cray-HPE/cray-site-init/pull/192/files
* `hermod`
I tested this with the net-attach-def set to ipvlan/hsn and macvlan/nmn. I pulled the new routes from a locally built `csi` using hermod seed files. The new routes are shown here:
```
routes:
- dst: 10.92.100.0/24        <-- new HMNLB
gw: 10.252.2.6
- dst: 10.254.0.0/17        <-- new HMN
gw: 10.252.2.6
- dst: 10.101.3.0/25
gw: 10.252.0.1
- dst: 10.94.100.0/24
gw: 10.252.2.6
- dst: 10.106.0.0/17
gw: …
```

CASMUSER-3028: Update cray-site-init to get changes for net-attach-def HMN routes

---

build/create-index.sh
packages/cray-pre-install-toolkit/base.packages
scripts/update-package-versions.sh

Use newer ilorest for CSM 1.3.
This one is also compatible with SLES15SP2 for upgrades if they ever jump from 1.0 to 1.3.

CASMTRIAGE-3600 SP2 Compatible ilorest

---

packages/cray-pre-install-toolkit/base.packages

A newer `libcft0` was being pulled in from the `autoinst.xml`, this caused a conflict when it came time to install `binutils`.
```bash
[ DEBUG   ]: 16:56:04 | Problem: the installed libctf0-2.37-150100.7.37.1.x86_64 requires 'libbfd-2.37.20211103-150100.7.37.so()(64bit)', but this requirement cannot be provided
[ DEBUG   ]: 16:56:04 |  Solution 1: downgrade of libctf0-2.37-150100.7.37.1.x86_64 to libctf0-2.37-150100.7.34.1.x86_64
[ DEBUG   ]: 16:56:04 |  Solution 2: do not install binutils-2.37-150100.7.34.1.x86_64
[ DEBUG   ]: 16:56:04 |  Solution 3: break libctf0-2.37-150100.7.37.1.x86_64 by ignoring some of its dependencies
[ DEBUG   ]: 16:56:04 | Choose from above solutions by number or cancel [1/2/3/c/d/?] (c): c
```
This pins the version so that the conflict won't occur.
This branch …

pin libctf0 so we stop pulling a newer one in that breaks binutils

---

packages/cray-pre-install-toolkit/base.packages

Add authentication to get-sqfs.sh (MTL-1799), include a bugfix for missing operands (MTL-1818).
Includes a fix for MTL-1806 regarding pit-init when SYSTEM_NAME isn't set.
Yes.

MTL-1799, MTL-1818,and MTL-1806

---

packages/node-image-kubernetes/metal.packages

The luks partition was failing to create in GCP on NVME. The addition from MTL-1748 ends up targeting a partition, but the luks commands need to target the entire disk. Furthermore the partition that's targeted doesn't exist.
This code block had been tested on hermod, but not thoroughly enough. Removing the block was tested on GCP and proved to work.

MTL-1748 Revert + README updates

---

.github/PULL_REQUEST_TEMPLATE.md
README.asc
packages/cray-pre-install-toolkit/base.packages
packages/cray-pre-install-toolkit/google.packages
packages/cray-pre-install-toolkit/metal.packages
packages/node-image-kubernetes/base.packages
packages/node-image-kubernetes/metal.packages
packages/node-image-non-compute-common/base.packages
packages/node-image-non-compute-common/google.packages
packages/node-image-non-compute-common/metal.packages
packages/node-image-storage-ceph/base.packages
packages/node-image-storage-ceph/google.packages
packages/node-image-storage-ceph/metal.packages

The current README is `.asc` but is formatted as Markdown, this fixes
that and then fills out some more details included how to add a package.
This also adds a PR template to replace the organizational wide template, which had several checkboxes that were not applicable to this repository.
Misc changes:
- Removal of `python-boto3` from `node-image-kubernetes`, this package is listed in `node-image-non-compute-common` and does not need to be listed in `node-image-kubernetes`. Listing it twice poses risk of an error, if someone updated `non-image-non-compute-common`'s `python-boto3` and didn't know it existed in `node-image-kubernetes`, then Kubernetes images would …

README and PULL_REQUEST_TEMPLATE

---

packages/node-image-non-compute-common/base.packages

DKMS is needed to dynamically build kernel modules to better support
asynchronous release of COS software.
- Fixes: MTL-1752
- Relates to: [SHASTAOS-1136](https://jira-pro.its.hpecorp.net:8443/browse/SHASTAOS-1136)
N/A

MTL-1752: add dkms to the NCN common layer

---

packages/cray-pre-install-toolkit/metal.packages
packages/node-image-non-compute-common/metal.packages

- Fixes: CASMINST-4914
Adds `kernel-firmware`, allowing NIC adapters to be viewable on QLogic equipped systems.

CASMINST-4914 Need kernel-firmware for QLogic

---

packages/compute-node.packages
packages/cray-pre-install-toolkit/base.packages
packages/node-image-non-compute-common/base.packages

Update craycli to 0.56.0
This brings the BOS comands up to date (0.54.0), removes the obsolete `cray network` subcommand from the CLI (0.55.0), and makes some minor fixes to BOS (0.56.0).
These changes are backward compatible.
* Resolves CASMCMS-8064
* Resolves [CASMCLOUD-1208](https://jira-pro.its.hpecorp.net:8443/browse/CASMCLOUD-1208) (0.55.0)
* Resolves CASMCMS-7876/CASMCMS-7848 (0.54.0)
The changes for 0.55.0 were tested by linting the code and running unit tests, then running the `cray network --help` command and verifying that there was no `network` sub-command supported.
The changes for 0.54.0 ad 0.56.0 (per the description provided by …

CASMCLOUD-1208 update craycli to 0.56.0

---

packages/node-image-kubernetes/metal.packages
packages/node-image-non-compute-common/metal.packages

- Fixes: MTL-1839
- Relates to: CASMTRIAGE-3591
These updates prevent the need to special-case metal dracut when building kdump metal dracut no longer has to be omitted.

MTL-1839 Better kdump handling

---

packages/cray-pre-install-toolkit/base.packages

- Fixes: CASMINST-3671 and CASMINST-3787
Pull in newer CSI version to pull in EX2500 cabinet support. For additional detail see: https://github.com/Cray-HPE/cray-site-init/pulls?q=is%3Apr+is%3Aclosed
- [] I have included documentation in my PR (or it is not required)
See https://github.com/Cray-HPE/cray-site-init/pulls?q=is%3Apr+is%3Aclosed

CASMINST-3671: Pull in newer CSI version to pull in EX2500 cabinet support

---

packages/node-image-kubernetes/base.packages

Move to updated cmstools that stops using the deprecated v1 HSM API and uses v2 instead.
It will be broken without this change, since v1 is gone in csm v1.3.

CASMCMS-8073: cmstools stop using deprecated HSMv1 API

---

packages/node-image-non-compute-common/base.packages

- Fixes: [CASMPET-5737](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5737)
This adds in a goss test for the space needed for Nexus in the 1.3 upgrade
Tested on mug with a pass with current required size.
There is now risk in a failing test. But this will prevent a failed upgrade due to Nexus filling up.

CASMPET-5737: Goss Test for Nexus Space On Upgrade

---

packages/cray-pre-install-toolkit/base.packages
packages/cray-pre-install-toolkit/metal.packages
packages/node-image-non-compute-common/base.packages
packages/node-image-non-compute-common/metal.packages

- Fixes: MTL-1853
Google builds do not invoke `metal.packages`, and thus are susceptible to having a newer kernel than metal. We want to lock the kernel overall, so this moves the kernel packages into `base.packages` to do just that.
**This does not fix the multiple kernel issue in MTL-1853**, this resolves a tangental issue discovered while fixing MTL-1853.

MTL-1853 Google Has Mismatching Kernel

---

packages/compute-node.packages
packages/cray-pre-install-toolkit/base.packages
packages/node-image-non-compute-common/base.packages

This removes the deprecated HSM v1 APIs from craycli
- Fixes: [CASMHMS-5628](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5628)
None

Update craycli rpm version to 0.58.0 to remove HSM v1 APIs

---

packages/node-image-non-compute-common/base.packages

- Fixes: [CASMPET-5756](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5756)
This updates the amount of space that is required free in Nexus. 
No risks added with this change

CASMPET-5756: Update Nexus required space test

---

packages/node-image-non-compute-common/base.packages

The new goss-servers is failing the NCN builds, this rolls back to 1.14.31.

Revert goss servers

---

packages/cray-pre-install-toolkit/base.packages

- Fixes: CASMINST-4940
See: https://github.com/Cray-HPE/cray-site-init/pull/204
This also brings in some dependency updates from dependabot:
- https://github.com/Cray-HPE/cray-site-init/pull/213
- https://github.com/Cray-HPE/cray-site-init/pull/214
- https://github.com/Cray-HPE/cray-site-init/pull/215
- https://github.com/Cray-HPE/cray-site-init/pull/216
- https://github.com/Cray-HPE/cray-site-init/pull/217
- https://github.com/Cray-HPE/cray-site-init/pull/218
- https://github.com/Cray-HPE/cray-site-init/pull/219
- https://github.com/Cray-HPE/cray-site-init/pull/220
- https://github.com/Cray-HPE/cray-site-init/pull/221

CASMINST-4940 Upgrade command changes + dependency updates

---

packages/node-image-kubernetes/base.packages

- Fixes: CASMTRIAGE-3784
- Requires: https://github.com/Cray-HPE/utils/pull/54
- Relates to: CASMINST-5051
Pulls in fixes for the spire token fix script where ssh may fail in certain conditions causing the script not to update the spire storage token and files.
- [x ] I tested this on internal system (if yes, please include results or a description of the test) Tyr, Drax, Fanta, Mug
As it stands if the cloud init join script fails, and this script is run, depending on what is in ~/.ssh and if the node is in authorized_hosts the fix script won't fix anything.

CASMTRIAGE-3784: Use 1.3.2 platform utils

---

packages/node-image-kubernetes/base.packages

- Fixes: [CASMCMS-8068](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8068)
- Source PR: https://github.com/Cray-HPE/cms-tools/pull/44
- csm manifest PR: https://github.com/Cray-HPE/csm/pull/1072
Adds the option for users to specify the image used in the barebones boot test. In some cases, the default of picking the first image with "barebones" in its name does not work. This allows a way to handle that, if it occurs.
I tested this on rocket, both with and without an ID being specified, to make sure that both cases still work correctly. I also tested to make sure it behaved appropriately if an invalid ID is specified.
Low risk -- the default behavior of the test is not changed. This only adds a new option. And this new option allows some people to be able to run …

CASMCMS-8068: Allow user to specify image used in barebones test

---

packages/cray-pre-install-toolkit/base.packages

- Fixes CASMUSER-3028
- Fixes CASMUSER-3050
CSI adds "routes" for the UAI net-attach-definition customizations to invalid IPs as a blackhole for traffic that should not go out the weave net over the default route.
Add two new routes for HMN and HMNLB.
I tested this with the net-attach-def set to ipvlan/hsn and macvlan/nmn. I pulled the new routes from a locally built `csi` using hermod seed files. The new routes are shown here:
```
routes:
- dst: 10.92.100.0/24        <-- new HMNLB
gw: 10.252.2.6
- dst: 10.254.0.0/17        <-- new HMN
gw: 10.252.2.6
- dst: 10.101.3.0/25
gw: 10.252.0.1
- dst: 10.94.100.0/24
gw: 10.252.2.6
- dst: 10.106.0.0/17
gw: 10.252.0.1
```
With a modified net-attach-def including these routes, I could not hit IPs on those networks as intended. …

CASMUSER-3050: Add hmnlb and hmn blackhole routes for UAI

---

packages/node-image-non-compute-common/metal.packages

- Fixes: MTL-1841
- Relates to: MTL-1830
The new `dracut-metal-mdsquash` RPM supports native `kdump` on our overlayFS.
See: https://github.com/Cray-HPE/dracut-metal-mdsquash/pull/45

MTL-1841 Native `kdump`

---

packages/node-image-non-compute-common/base.packages

See source PRs for details:
https://github.com/Cray-HPE/csm-testing/pull/348
https://github.com/Cray-HPE/csm-testing/pull/347
- Fixes: [CASMINST-5124](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5124)
- Fixes: [CASMINST-5129](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5129)
Fixed a build issue and a test issue.
Without these changes, one of the goss test scripts does not work, and the goss-servers RPM cannot be updated to a new version in the NCN images.

CASMINST-5124/CASMINST-5129: Fix NCN image build issue, Fix typo in ncn-healthcheck-master script

---

packages/cray-pre-install-toolkit/base.packages
packages/node-image-non-compute-common/base.packages

- Fixes: MTL-1867
Base images are building with too new of a libelf1 library that conflicts with our pinned kernel version, this is causing full NCN builds (builds of the base image) to fail.

MTL-1867 Pin libelf1

---

packages/node-image-kubernetes/metal.packages
packages/node-image-non-compute-common/metal.packages

- Fixes: MTL-1863
On install or update of the dracut RPMs the initrd and kdump initrd will be updated. This was tested and worked, the kdump initrd is only updated if kdump is installed.
See:
- https://github.com/Cray-HPE/dracut-metal-mdsquash/pull/49
- https://github.com/Cray-HPE/dracut-metal-luksetcd/pull/39
- https://github.com/Cray-HPE/dracut-metal-dmk8s/pull/29

MTL-1863 Invoke `mkinitrd` on update/install

---

packages/node-image-non-compute-common/base.packages

- Fixes: [CASMINST-5159](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5159)
Significantly speeds up the display of Goss test results.
See source PR for details: https://github.com/Cray-HPE/csm-testing/pull/349
See source PR for details: https://github.com/Cray-HPE/csm-testing/pull/349
Low risk because the change is only to the code for displaying test results. No tests changed.

CASMINST-5159: Speed up Goss test result reporting

---

packages/node-image-kubernetes/base.packages
packages/node-image-non-compute-common/base.packages

Adding the container (-c etcd) when exec'ing into the etcd pods.
This covers changes needed for:
** ncnHealthCHecks.sh (utils)
** goss tests (csm-testing)
** md docs (docs-csm)
This change is not needed for csm 1.0 or 1.2.
Is this change backwards incompatible, backwards compatible, or a backwards compatible bugfix? bug fix
* Resolves [CASMPET-5838](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5838)
* Change will also be needed in NA (only needed for CSM 1.3 and beyond)
drax
* `drax`
Ran ncnHealthChecks and goss test to verify no regressions in the fix. …

CASMPET-5838-1.3 : Break/Fix: Etcd health checks failing - need to specify etcd container

---

packages/cray-pre-install-toolkit/base.packages
packages/cray-pre-install-toolkit/metal.packages
packages/node-image-non-compute-common/base.packages
packages/node-image-non-compute-common/metal.packages

- Relates to: MTL-1865
This package is a dependency for `mft`, which is only installed via `metal.packages`.
This package has no use in Google nor Vagrant, and is actually causing the Vagrant builds to slow down (it takes a long time to install). This moves it into the proper context.

MTL-1865 Move `kernel-mft-mlnx-kmp-default`

---

packages/node-image-non-compute-common/base.packages

- Fixes: [CASMINST-5161](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5161)
csm repo PR: https://github.com/Cray-HPE/csm/pull/1125
Modify automated Goss scripts so that they only print failure information to screen, and successes to a log file.
See source PR for testing details: https://github.com/Cray-HPE/csm-testing/pull/355
Medium risk, but big payoff in usability.

CASMINST-5161: Reduce excessive Goss script output

---

packages/node-image-kubernetes/base.packages
packages/node-image-non-compute-common/base.packages
repos/cray.repos

Some RPMs for COS were floating in the general list, additionally this organizes the `cray.repos` file to put the removable repos last.

MTL-1878 Make teams more clear

---

packages/cray-pre-install-toolkit/base.packages

Overview
BUGFIX: Fix UAN configuration templates producing None VLAN when CHN is enabled.
BUGFIX: Enable 1.3 configuration templates in the pyinstaller binary.
Details
Update docs generated from code.
Change exception-handling in canu validate shcd and from network_modeling.
Provide better next steps from errors reported while validating SHCDs.
Add canu test to ping Kea DHCP.
Update to release process doc
- Fixes: CASMNET-1757
- Bugfix [Release 1.6.13](https://github.com/Cray-HPE/canu/pull/196)

CASMNET-1757: CANU bugfixes including UAN VLAN as None

---

packages/cray-pre-install-toolkit/base.packages

Updates pit-init to include new get-sqfs.sh script for that progress bar/eta goodness.
- Fixes: CASMINST-5209
- Requires:
- Relates to:
- [x ] I tested this on internal system redbull
Not very risky, and if it isn't pulled in get-sqfs.sh just doesn't have progress bars or an eta.

CASMINST-5209 update pit-init

---

packages/node-image-kubernetes/base.packages
repos/cray.repos

Reverts Cray-HPE/csm-rpms#542 and re-applies it with the proper version.

Revert "CRAYSAT-1509: Add cray-sat-podman version 2.0.0 to NCN image"

---

packages/compute-node.packages
packages/cray-pre-install-toolkit/base.packages
packages/node-image-non-compute-common/base.packages

This updates the cli to match the final api for BOS v2, and switches the cli to start hitting the v2 endpoint if no version is specified.
This updates the cli to match the final api for BOS v2
None

CASMCMS-8090: Update craycli for latest BOS v2 changes

---

packages/node-image-kubernetes/base.packages
repos/cray.repos

- Fixes: HPCCHT3-3379 "cray-sdu-rda-2.1.0-shasta release" 
This change is to update the version of cray-sdu-rda for the Papaya RC1 8/12 release in the base NCN image. This change needs to be in the CSM 1.3 release branch, please.
Low risk installation of a benign RPM that doesn't do anything other than place files in the base OS. This RPM becomes functional post recipe installation.

Update to cray-sdu-rda-2.1.0 in base.packages for CSM 1.3, Papaya RC1 8/12/22

---

packages/node-image-kubernetes/base.packages

Fixes cmsdev test false failure. See source PR for details:
https://github.com/Cray-HPE/cms-tools/pull/48
- Fixes: [CASMINST-5240](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5240)
- Relates to: [CASMCMS-8087](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8087)
- csm manifest PR: https://github.com/Cray-HPE/csm/pull/1164
Fixes cmsdev test false failure. See source PR for details:
https://github.com/Cray-HPE/cms-tools/pull/48
Very low risk -- two subtests are removed. No changes to anything else.

CASMINST-5240: Disable cmsdev testing of BOS CLI without explicitly specifying the version

---

packages/node-image-kubernetes/base.packages

Backport of https://github.com/Cray-HPE/csm-rpms/pull/555

CASMINST-5240: Disable cmsdev testing of BOS CLI without explicitly specifying the version (#555)

---

packages/node-image-non-compute-common/metal.packages

Kernel isn't pinned, making rebuilds of 1.2 NCNs pull in newer kernels.

Fix 1.2 pinning of kernel

---

packages/node-image-kubernetes/metal.packages
packages/node-image-non-compute-common/base.packages
packages/node-image-non-compute-common/metal.packages

- Relates to: MTL-1865 CASMTRIAGE-3944
Several packages such as `tpm` and `mft` can have hardware emulated from
Vagrant or Vshasta. This simply reshuffles the packages to ensure
someone testing a Vagrant box or Vshasta image can validate basics like
kernel packages.

Support Virtualization

---

packages/node-image-pre-install-toolkit/base.packages

- Fixes: CASMPET-5428
Fixes for `cephExporter` endpoints.
Brings in some dependency/library updates.

CASMPET-5428 `cray-site-init`

---

packages/node-image-common/metal.packages

- Fixes: MTL-1925
This fixes the IPv4-only mode, which was being ignored before.

MTL-1925 `dracut-metal-mdsquash` fix `metal.ipv4`

---

packages/node-image-kubernetes/metal.packages

- Fixes: MTL-1924
This fixes the calls to `partprobe` when NVME is in use.

MTL-1924 `dracut-metal-dmk8s` fix NVME `partprobe`

---

packages/node-image-kubernetes/base.packages

main backport of https://github.com/Cray-HPE/csm-rpms/pull/576

CASMCMS-8087: Add BOSv2 support to cmsdev test tool

---

packages/node-image-kubernetes/base.packages
repos/cray.repos

Test Description:
- Fixes: CRAYSAT-1476
This change updates the version of the prodmgr RPM to the new stable
release. The old arti.dev.cray.com repo was also removed.
Build kubernetes node image and confirm the correct RPM versions are
present.
This change updates `prodmgr`. If including the new version introduces errors, the new version can be rolled back.

CRAYSAT-1476: Update prodmgr to stable version

---

packages/node-image-kubernetes/base.packages

main backport of https://github.com/Cray-HPE/csm-rpms/pull/582
This should merge at the same time as the following PRs:
https://github.com/Cray-HPE/csm/pull/1224
https://github.com/Cray-HPE/csm/pull/1220
https://github.com/Cray-HPE/csm-rpms/pull/588

CASMCMS-8193: cmsdev test: Update BOS CLI test to reflect default version back to v1

---

packages/node-image-common/base.packages
packages/node-image-compute/base.packages

See https://github.com/Cray-HPE/csm/pull/1220
This should merge at the same time as the following PRs:
https://github.com/Cray-HPE/csm-rpms/pull/582
https://github.com/Cray-HPE/csm/pull/1224
https://github.com/Cray-HPE/csm/pull/1220

CASMCMS-8192: Default the Cray CLI to v1 for BOS

---

packages/node-image-kubernetes/base.packages

- Fixes: [CASMCMS-8203](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8203)
- Relates to: [CASMTRIAGE-4074](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-4074)
The cmsdev test crashes in a couple of error paths when it dereferences null pointers. The fix is very simple.
Tested on starlord, where the problem was discovered. See source PR for details: https://github.com/Cray-HPE/cms-tools/pull/57
Very low risk to include. Fix is extremely simple.

CASMCMS-8203: Stop failing git commands from crashing cmsdev

---

packages/node-image-common/base.packages
packages/node-image-compute/base.packages

- Fixes: [CASMCLOUD-1212](https://jira-pro.its.hpecorp.net:8443/browse/CASMCLOUD-1212)
Update craycli to 0.63.0 to fix python 3.6 deprecation warning.
Ran the offending command from the ticket and verified that the deprecation warning no longer occurs.
The risk for this is low since we are simply moving the boto3 and botocore modules back to previously used versions in the CLI.  Without this fix, users see a potentially unsettling deprecation warning that has no bearing on actual reality because of the way the CLI is packaged and installed.

Update craycli to 0.63.0; fix python3.6 deprecation warning

---

packages/compute-node.packages
packages/cray-pre-install-toolkit/base.packages
packages/node-image-non-compute-common/base.packages

- Fixes: [CASMCLOUD-1212](https://jira-pro.its.hpecorp.net:8443/browse/CASMCLOUD-1212)
Update craycli to 0.63.0 to fix python 3.6 deprecation warning.
Ran the offending command from the ticket and verified that the deprecation warning no longer occurs.
The risk for this is low since we are simply moving the boto3 and botocore modules back to previously used versions in the CLI.  Without this fix, users see a potentially unsettling deprecation warning that has no bearing on actual reality because of the way the CLI is packaged and installed.

Update craycli to 0.63.0; fix python 3.6 deprecation warning

---

packages/node-image-kubernetes/base.packages

- Fixes: [CASMCMS-8210](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8210)
- Adds 3 overlooked BOS CLI tests to the cmsdev test tool. See source PR for full details: https://github.com/Cray-HPE/cms-tools/pull/58
- Fixed [CASMCMS-8212](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8212)
- Updated Golang version and dependent modules to [resolve High severity CVE](https://github.com/Cray-HPE/cms-tools/security/dependabot/1). See source PR for full details: https://github.com/Cray-HPE/cms-tools/pull/60
New subtests were run successfully on surtur. See source PR for full details:
https://github.com/Cray-HPE/cms-tools/pull/58
Rebuilt binary with CVE remediations was tested on fanta. See source PR for full details: https://github.com/Cray-HPE/cms-tools/pull/60 …

CASMCMS-8210/CASMCMS-8212: cmsdev: Add BOS CLI tests, resolve CVE

---

packages/node-image-kubernetes/base.packages
repos/cray.repos

[HPCCHT3-3457](https://jira-pro.its.hpecorp.net:8443/browse/HPCCHT3-3457) : "Build, test and release cray-sdu-rda-2.1.1"
- Fixes: See the [release page](https://jira-pro.its.hpecorp.net:8443/projects/HPCCHT3/versions/58373) for details on what is going into this release.
- Requires: N/A
- Relates to: N/A
This will update the cray-sdu-rda RPM installation into the base NCN image from cray-sdu-rda-2.1.0 to cray-sdu-rda-2.1.1. Additionally, the base URL from which to retrieve the RPM has been updated.
All of the changes in this release are either bug fixes or documentation changes. As a result, the risk is overall reduced.
The main bug fix in this release was a segmentation fault that was encountered at cray-sdu-rda service start up time when …

HPCCHT3-3457 cray-sdu-rda 2.1.1

---

packages/node-image-pre-install-toolkit/base.packages

- Relates to: MTL-1695
This CSI just deprecates a function that was yanked out of the CSM 1.3 docs.
See: https://github.com/Cray-HPE/cray-site-init/pull/256

MTL-1695 Edge work

---

packages/cray-pre-install-toolkit/base.packages

- Relates to: MTL-1695
This CSI just deprecates a function that was yanked out of the CSM 1.3 docs.
See: https://github.com/Cray-HPE/cray-site-init/pull/255

MTL-1695 Edge work and MTL-1961 Redo

---

.github/PULL_REQUEST_TEMPLATE.md
Jenkinsfile.github
packages/node-image-common/vagrant.packages
packages/node-image-kubernetes/vagrant.packages
packages/node-image-pre-install-toolkit/vagrant.packages
packages/node-image-storage-ceph/vagrant.packages

- Relates to: CASMINST-5313
The `qemu-guest-agent` package was being slurped into Dennis' repacking of the `.qcow2` files when making a `.box`. To use native boxes we need to install this into the native boxes during the build, then we don't need to repack it like Dennis is currently doing.
This adds a `vagrant.packages` files.

CASMINST-5313 Vagrant OS Test Harness Deps.

---

packages/node-image-kubernetes/base.packages

[HPCCHT3-3493](https://jira-pro.its.hpecorp.net:8443/browse/HPCCHT3-3493)
[release notes](https://jira-pro.its.hpecorp.net:8443/projects/HPCCHT3/versions/58922) for the changes needed for the cray-sdu-rda-2.1.2 release targeting Papaya: 
The main goal of these changes is to fix a minor bug related to cray-sdu-rda version transitioning.
- Test results found [here](https://github.hpe.com/hpe/hpc-ch-sdu-tarfile-shasta/tree/d05317c39977af72c2781106e45ce2993246b930/testing/HPCCHT3-3493_2.1.2_release).

HPCCHT3-3493 build test release cray sdu rda 2.1.2 shasta release

---

packages/node-image-kubernetes/base.packages

[HPCCHT3-3493](https://jira-pro.its.hpecorp.net:8443/browse/HPCCHT3-3493)
[release notes](https://jira-pro.its.hpecorp.net:8443/projects/HPCCHT3/versions/58922) for the changes needed for the cray-sdu-rda-2.1.2 release targeting Papaya: 
The main goal of these changes is to fix a minor bug related to cray-sdu-rda version transitioning.
- Test results found [here](https://github.hpe.com/hpe/hpc-ch-sdu-tarfile-shasta/tree/d05317c39977af72c2781106e45ce2993246b930/testing/HPCCHT3-3493_2.1.2_release).

HPCCHT3-3493 Increment to cray-sdu-rda-2.1.2

---

build/resolve-packages.sh
packages/node-image-kubernetes/base.packages
repos/cray.template.repos
scripts/rpm-functions.sh

- Fixes: https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5422
- Relates to: https://jira-pro.its.hpecorp.net:8443/browse/MTL-1887
We're moving to github actions runners which do not have access to internally hosted artifacts required for builds.
- removes two unnecessary packages (cray-cps-utils and cray-orca) see Dean's comments in: https://jira-pro.its.hpecorp.net:8443/browse/MTL-1879
- makes cray.repos -> cray.template.repos to allow auth for artifactory.algol60.net
- updates COS / SDU repo locations (now on artifactory.algol60.net)
- updates rpm-functions.sh to support cray templated repos 
Minimal risk. This is part of a greater effort to move away from build dependencies on internal HPE systems.

CASMINST-5422

---

packages/node-image-non-compute-common/base.packages

The script that configures SNMP on Dell and Aruba switches expects a user to delete from the Aruba switches. Unfortunately the delete happens after the creation of the new user and if they are the same name, the new user is deleted leaving the switch as it was before the script is executed. Updated the script to not require the delete user name. This allows both a creation method and a way to delete bad user names.
Behavior will not change when the same command line from the documentation is used.
* Resolves [CASMHMS-5782](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5782)
* Documentation changes required in [CASMHMS-5782](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5782)
* `loki`
Copied a modified version of the script to loki and executed with an alternative username …

CASMHMS-5783 Fix snmp configure script

---

packages/node-image-non-compute-common/base.packages

The script that configures SNMP on Dell and Aruba switches expects a user to delete from the Aruba switches. Unfortunately the delete happens after the creation of the new user and if they are the same name, the new user is deleted leaving the switch as it was before the script is executed. Updated the script to not require the delete user name. This allows both a creation method and a way to delete bad user names.
Behavior will not change when the same command line from the documentation is used.
* Resolves [CASMHMS-5782](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5782)
* Documentation changes required in [CASMHMS-5782](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5782)
* `loki`
Copied a modified version of the script to loki and executed with an alternative username …

CASMHMS-5782 Fix snmp configure script

---

packages/node-image-common/base.packages

- Fixes: CASMCLOUD-1214
Built against Python3.10 to keep the code current, and built with updated dependencies.
- https://github.com/Cray-HPE/manifestgen/pull/17
- https://github.com/Cray-HPE/manifestgen/pull/18
- https://github.com/Cray-HPE/manifestgen/pull/19
- https://github.com/Cray-HPE/manifestgen/pull/20
- https://github.com/Cray-HPE/manifestgen/pull/22
`manifestgen` successfully produces a `manifest.yaml` file, and all unit tests pass.
```bash
redbull-ncn-m001-pit:/var/www/ephemeral/prep # manifestgen --version
manifestgen 1.3.8
redbull-ncn-m001-pit:/var/www/ephemeral/prep # rpm ^C
redbull-ncn-m001-pit:/var/www/ephemeral/prep # cd ^C
redbull-ncn-m001-pit:/var/www/ephemeral/prep # rm manifest.yaml
(reverse-i-search)`manife': rpm -Uvh …
```

CASMCLOUD-1214 Newer `manifestgen`

---

packages/node-image-pre-install-toolkit/base.packages

Add cilium-operator-replicas, k8s-primary-cni, and kube-proxy-replacement to CSI.

CASMPET-6145:  Bump cray-site-init to 1.28.0

---

packages/node-image-ncn-common/base.packages

- Fixes: CASMCMS-5516
Add `cfs-debugger`.
Signed-off-by: Russell Bunch <doomslayer@hpe.com>

CASMCMS-5516 `cfs-debugger`

---

packages/node-image-pre-install-toolkit/base.packages

- Fixes: MTL-1476
`mtools` provides `mmd` which is being used in the ISO creation script when creating the `efiboot.img`. `mmd` allows creation of subdirectories within the EFI image file.

MTL-1476 Add `mtools`

---

packages/node-image-application/base.packages

- Relates to: #663 
Stock SLES UAN currently aligns to the compute image. Adds `cray-chrony-dracut` and swaps `csm-node-identity` for `cray-node-identity` to align with compute images.

MTL-2004 `cray-chrony-dracut` for UAN

---

packages/node-image-pre-install-toolkit/base.packages

- Relates to: MTL-1708
New RPM was built against Python 3.10.8 vs. Python 3.10.4 and includes the correct SP4 build meta.

MTL-1708 Include updated canu RPM

---

Jenkinsfile.github
repos/cray.template.repos

Add artifactory authentication for zypper repos and docker
https://jira-pro.its.hpecorp.net:8443/browse/MTL-2045
artifactory.algol60.net is in the process of being locked down, so authentication will soon be required for accessing all repos.
Minimal risk. The authentication method we're using is already used in this repo and others.

MTL-2045 artifactory auth

---

packages/node-image-base/base.packages

- Requires: https://github.com/Cray-HPE/csm/pull/1584
- RFE Pull Request: [CASMHMS-5771](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5771)
Removed the SLS option to get credentials. This removes the options to pass public and private keys to sls dumpstate and loadstate.
This is low risk. It removes cray cli features that we believe the customer does not use. The removed cray cli options only recently started working.

CASMHMS-5771 cray cli 0.66.0

---

packages/node-image-base/base.packages

- Fixes: CASMTRIAGE-4697
Back the kernel version off of 5.14.21-150400.24.33.2 and down to 5.14.21-150400.22.1. The oldest 5.14.21 kernel we have. This works around a kernel panic, all of the 150400.24 patch kernels we have lead to a panic during the CSM install.

CASMTRIAGE-4697 Downgrade the kernel

---

packages/node-image-base/base.packages

- Relates to: CASMTRIAGE-4697
This reverts commit 2000860ec60c4652d383dcb5b435cbaa5f27d56a.
MTL-2053 was successful, so we will not downgrade the kernel but instead use the official PTF kernel that includes a patch for CASMTRIAGE-4697.

Revert "CASMTRIAGE-4697 Downgrade the kernel (#681)"

---

packages/node-image-base/base.packages
repos/suse.template.repos

- Fixes: CASMTRIAGE-4697
Pull in the PTF update from SUSE which includes the vetted fix for CASMTRIAGE-4697.
This updates the kernel to `5.14.21-150400.24.38.1.25440.1.PTF.1204911`.

CASMTRIAGE-4697 Kernel update

---

packages/node-image-base/base.packages
packages/node-image-compute/base.packages
packages/node-image-ncn-common/base.packages

- Fixes: MTL-2058
Numerous misc. package updates to pull in before we ship 1.4.0-alpha.29. 1.4.0-alpha.29 has the working/fixed SP4 kernel, that makes 1.4.0-alpha.29 the first CSM 1.4 release with SP4 that other teams can use. This means we will be inspecting CVEs much more closely, so taking another stab at updating to the most recent latest of thes packages is a good idea.
This also moves some packages out of node-image-ncn-common and into base, namely:
- mft
- kernel-mft-mlnx-kmp-default
This also removes csm-node-identity from node-image-ncn-common because it is already defined in node-image-base.

MTL-2058 Package updates

---

packages/node-image-ncn-common/base.packages

- Fixes: [CASMINST-5793](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5793)
- [1.4 source PR](https://github.com/Cray-HPE/csm-testing/pull/427)
- [main source PR](https://github.com/Cray-HPE/csm-testing/pull/428)
- [1.4 csm manifest PR](https://github.com/Cray-HPE/csm/pull/1633)
- [main csm manifest PR](https://github.com/Cray-HPE/csm/pull/1634)
- [main csm-rpms manifest PR](https://github.com/Cray-HPE/csm-rpms/pull/698)
In csm-testing, print_goss_json_results was logging test duration in seconds using scientific notation (this was happening implicitly, by the Python JSON module). This was unable to be consumed by the grok exporter tool being used to collect the Goss test logs. This PR changes things so that scientific notation is not …

CASMINST-5793: csm-testing: Log test duration in decimal without scientific notation

---

packages/node-image-application/base.packages
packages/node-image-compute/base.packages
packages/node-image-ncn-common/base.packages
repos/compute.template.repos
repos/cray.template.repos

Brings in COS 2.5, and does not upgrade `spire-agent`.

CASMPET-5081 COS 2.5

---

packages/node-image-application/base.packages
packages/node-image-compute/base.packages
packages/node-image-ncn-common/base.packages

Brings in COS 2.5, and does not upgrade `spire-agent`.
This is amending the PR that already merged: https://github.com/Cray-HPE/csm-rpms/pull/701

CASMPET-5081 COS 2.5 with spire 0.12.2

---

packages/node-image-pre-install-toolkit/base.packages

Brings in newer `write-livecd.sh` script with support for the new ISO.

MTL-1476 New `cray-site-init`

---

packages/node-image-kubernetes/base.packages

- Fixes: MTL-2068
`cri-tools-1.26.0-0` is now available, but it is incompatible with our version of `containerd`. Since `cri-tools` was not pinned, the newer `cri-tools` was being pulled in and causing NCN image builds to fail.
This pins the `cri-tools` package to the version used in our most recent, working NCN image build (`1.25.0`). Without this pin, our Kubernetes NCN image will fail to build.

MTL-2068 Pin `cri-tools`

---

packages/node-image-base/base.packages

(cherry picked from commit 316f8780aa553781393daa6793e3b0196e20ed1f)
main backport of https://github.com/Cray-HPE/csm-rpms/pull/712

CASMCMS-8380: Minor language and formatting corrections to CFS Cray CLI

---

packages/node-image-application/base.packages
packages/node-image-compute/base.packages
packages/node-image-ncn-common/base.packages

- Relates to: #706 
`spire-agent` was rebuilt, the content is the same. This `spire-agent` change just aligns what's installed to what COS inventory says is current.
This found an update for `cray-heartbeat` for application and compute, the commit hash is the same.

COS 2.5 align `cray-heartbeat` and `spire-agent`

---

packages/node-image-ncn-common/base.packages
packages/node-image-storage-ceph/base.packages

upsteam stopped providing our currently installed version.
- Fixes: [CASMINST-5861](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5861)
- Requires:
- Relates to:

CASMINST-5861 - bump ceph version

---

packages/node-image-pre-install-toolkit/base.packages

- Fixes: CASMMON-250
- Requires: https://github.com/Cray-HPE/pit-observability/pull/5
- Relates to: #62 #60 
Do not `restart` the services, they operate with better success if they're `start`ed. This stops them for consistency, and then enables and starts them in one call.

CASMMON-250: Failed to start prometheus and grok-exporter

---

packages/node-image-pre-install-toolkit/base.packages

CASMMON-250: Failed to start prometheus operator with pit-init
* Resolves - https://jira-pro.its.hpecorp.net:8443/browse/CASMMON-250
redbull-pit
redbull-ncn-m001-pit: # podman ps
CONTAINER ID  IMAGE                                                                                   COMMAND               CREATED        STATUS             PORTS       NAMES
28aa25485756 …

CASMMON-250

---

packages/node-image-base/base.packages

Updates the craycli to include the BOS clear-state option.  Also pulls in some linting changes.
* Resolves CASMCMS-8301
See craycli PRs for testing info
None

CASMCMS-8301: Update craycli to 0.68.0 for new BOS fields 91.4)

---

packages/node-image-base/base.packages

- Fixes: [CASMCMS-8399](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8399)
- Relates to: [CASMCMS-8396](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8396)
- [csm manifest PR](https://github.com/Cray-HPE/csm/pull/1754)
Remove CRUS from the Cray CLI.
Low risk. And since the tickets to remove CRUS have already merged, leaving it in the CLI is a bold move.

CASMCMS-8399: Remove CRUS from Cray CLI

---

packages/node-image-application/base.packages
packages/node-image-base/base.packages
packages/node-image-compute/base.packages
packages/node-image-kubernetes/google.packages
packages/node-image-ncn-common/base.packages
repos/suse.template.repos

- Relates to: MTL-2074
Includes a new kernel (replacing the PTF kernel), and several non-kernel package updates.
Includes the following CVE fixes:
- https://www.suse.com/security/cve/CVE-2023-0417.html
- https://lists.suse.com/pipermail/sle-security-updates/2023-January/013529.html
***This pull-request is a partial update, it pulls all the available packages***. Some CVE updates for MTL-2074 are not released yet. This change at least pulls in some items like the kernel to get them earlier soak time.

CSM 1.5.0 Updates (Partial MTL-2074)

---

packages/node-image-kubernetes/metal.packages
packages/node-image-ncn-common/metal.packages

- Fixes: VSHA-536
Brings in:
- https://github.com/Cray-HPE/dracut-metal-mdsquash/pull/56
- https://github.com/Cray-HPE/dracut-metal-luksetcd/pull/42
- https://github.com/Cray-HPE/dracut-metal-dmk8s/pull/33
This adds `virtio` support for supporting Google standard-disks as well as bugfixes for edge cases.

VSHA-536 Add `virtio` support

---

packages/node-image-ncn-common/metal.packages

- Relates to: VSHA-536
The auto-wipe needed some more deterministic wipe steps for handling equal handling in metal and vshastav2.
See: https://github.com/Cray-HPE/dracut-metal-mdsquash/pull/58

VSHA-536 Fixes for auto-wipe

---

packages/node-image-ncn-common/metal.packages

- Relates to: #751 
Look for disks with `-ge` instead of `-gt` to be inclusive of disks that are `==` to our minimum requirement.

VSHA-536 Incorporate `-ge` byte comparison

---

packages/node-image-pre-install-toolkit/base.packages

- Fixes: MTL-2103
`cray-site-init`:
- https://github.com/Cray-HPE/cray-site-init/pull/283
- https://github.com/Cray-HPE/cray-site-init/pull/285
- https://github.com/Cray-HPE/cray-site-init/pull/286
- https://github.com/Cray-HPE/cray-site-init/pull/287
`metal-basecamp`:
- https://github.com/Cray-HPE/metal-basecamp/pull/35
- https://github.com/Cray-HPE/metal-basecamp/pull/38
- https://github.com/Cray-HPE/metal-basecamp/pull/34

MTL-2103 Dependency updates for metal-basecamp and csi

---

packages/node-image-kubernetes/base.packages
packages/node-image-ncn-common/base.packages

- Modifies cmsdev tool to omit tftp file transfer subtest on master NCNs
- Updates Goss suite to run that test on worker NCNs
- [csm-rpms main backport manifest PR](https://github.com/Cray-HPE/csm-rpms/pull/781)
- [csm 1.4 manifest PR](https://github.com/Cray-HPE/csm/pull/1963)
- [csm main backport manifest PR](https://github.com/Cray-HPE/csm/pull/1964)
- Resolves [CASMCMS-8473](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8473)
- Problem created by the change made in [CASMCMS-8450](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8450)
- Problem reported by [CASMTRIAGE-5071](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-5071)
- [cmsdev test tool source PR](https://github.com/Cray-HPE/cms-tools/pull/73)
- [csm-testing Goss source …

CASMCMS-8473: Run tftp file transger subtest on workers not masters

---

packages/node-image-kubernetes/base.packages

To help @mtupitsyn add cmsdev to Goss, this adds a feature to cmsdev that lists the available tests it can run.
In addition, a null pointer exception is fixed (but this is only hit when using cmsdev in an unadvertised way and before CSM is deployed -- so not a critical problem).
See source PRs for details.
- [CASMCMS-8479 source PR](https://github.com/Cray-HPE/cms-tools/pull/76)
- [CASMCMS-8480 source PR](https://github.com/Cray-HPE/cms-tools/pull/77)
- Resolves [CASMCMS-8479](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8479)
- Resolves [CASMCMS-8480](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8480)
- [csm 1.4 manifest PR](https://github.com/Cray-HPE/csm/pull/1993)
- [csm main manifest PR](https://github.com/Cray-HPE/csm/pull/1994)
- [csm-rpms main manifest …

CASMCMS-8479/CASMCMS-8480: cmsdev: Add feature to list available tests; fix minor bug

---

packages/node-image-kubernetes/base.packages

Functionally no change to this RPM (just backend changes to the build process and the repo). But I'd rather keep the manifest at the latest version in this case, so that if we need to make later changes, it will be on top of this version.
See [source PR](https://github.com/Cray-HPE/cms-tools/pull/80) for details.
[csm-rpms main manifest PR](https://github.com/Cray-HPE/csm-rpms/pull/795)
This is going into the csm manifest repo as part of these combo manifest PRs:
https://github.com/Cray-HPE/csm/pull/1993
https://github.com/Cray-HPE/csm/pull/1994

CASMCMS-8482: cmsdev repository cleanup (remove binary from repo, stop building SP3 RPM)

---

packages/node-image-base/base.packages

This new craycli RPM makes BOS V2 the default version used when a 'cray bos <command>' is issued without specifying a version.
- Relates to: CASMCMS-8481

CASMCMS-8481: Make BOS V2 the default for cray cli BOS commands

---

packages/cray-pre-install-toolkit/base.packages

Include CANU 1.7.0 in CSM base packages.  Includes dozens of bugfixes as well as customer acceptance required changes.
- Fixes: JIRA (CASMNET-2056)
Full gamut of changes at:  https://github.com/Cray-HPE/canu/releases/tag/1.7.0

CASMNET-2056 Canu-1.7.0-1.3

---

packages/node-image-pre-install-toolkit/base.packages

Include CANU 1.7.0 in CSM base packages.  Includes dozens of bugfixes as well as customer acceptance required changes.
- Fixes: JIRA (CASMNET-2056)
Full gamut of changes at:  https://github.com/Cray-HPE/canu/releases/tag/1.7.0

CASMNET-2056 Bump canu to 1.7.0

---

packages/node-image-kubernetes/base.packages

Update cmsdev test tool to reflect change in Cray CLI defaults. See [source PR](https://github.com/Cray-HPE/cms-tools/pull/87) for details.
- [Source PR](https://github.com/Cray-HPE/cms-tools/pull/87)
- Test failures caused by [CASMCMS-8481](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8481)
- Resolves [CASMCMS-8495](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8495)
- [csm main manifest PR](https://github.com/Cray-HPE/csm/pull/2043)
- [csm 1.4 manifest PR](https://github.com/Cray-HPE/csm/pull/2044)
- [csm-rpms 1.4 manifest PR](https://github.com/Cray-HPE/csm-rpms/pull/805)
See [source PR](https://github.com/Cray-HPE/cms-tools/pull/87) for details.
Without this change, the cmsdev bos test will fail on all CSM 1.4+ systems.

CASMCMS-8495: cmsdev: Update default CLI BOS version to v2

---

packages/node-image-pre-install-toolkit/base.packages

Include CANU 1.7.1 in CSM base packages.  Rolls back a python library in CANU that broke the RPM build.
- Fixes: JIRA (CASMNET-2056)
https://github.com/Cray-HPE/canu/releases/tag/1.7.1

CASMNET-2056 1.4

---

packages/node-image-pre-install-toolkit/base.packages

Include CANU 1.7.1 in CSM base packages.  Rolls back a python library in CANU that broke the RPM build.
- Fixes: JIRA (CASMNET-2056)
https://github.com/Cray-HPE/canu/releases/tag/1.7.1

CASMNET-2056 main

---

packages/node-image-kubernetes/base.packages

Dependabot reported a couple of CVEs in dependencies of cms-tools.
They aren't critical CVEs and I suspect we aren't using the affected code in a way that would cause us problems, but may as well update the dependencies to avoid the risk. This does that.
I am not backporting to 1.3 since they are not big issues and I don't think we're shipping more RPMs for 1.3. I will backport to 1.4 however.
- [csm main manifest PR](https://github.com/Cray-HPE/csm/pull/2064)
- [csm 1.4 manifest PR](https://github.com/Cray-HPE/csm/pull/2065)
- [csm-rpms 1.4 manifest PR](https://github.com/Cray-HPE/csm-rpms/pull/810)
I tested on wasp to make sure no regressions were introduced.
Low risk.

CASMCMS-8502: cmsdev: Update dependencies to resolve CVEs

---

repos/hpe.template.repos

- Fixes: CASMINST-6100
The hpe-spp mirror is no longer updated, switch to the new hpe-spp-gen10 mirror.

CASMINST-6100 Change to new HPE SPP mirror

---

packages/node-image-base/base.packages

- Fixes: MTL-2138
- Relates to: CASMTRIAGE-5033
The 8.72 QLogic FastLinq driver will help protect against kernel panics seen by CASMTRIAGE-5033's root cause.
This does not fix the root cause of CASMTRIAGE-5033, loss of connectivity is still expected.

MTL-2138 Pull in OOB QLogic FastLinq Driver

---

packages/node-image-base/base.packages

- Fixes: CASMCLOUD-1219
- Relates to: https://github.com/Cray-HPE/craycli/pull/81
Modernized `craycli` based on Python 3.10.

CASMCLOUD-1219 New `craycli`

---

scripts/rpm-functions.sh

When the fake conntrack RPM is setup, `rpmbuild` and `createrepo_c` are needed temporarily. These two packages bring in several dependencies that do not get cleaned up.
Clean these up by using `--clean-deps` during their removal.
Before:
```bash
qemu.hypervisor: The following 37 NEW packages are going to be installed:
qemu.hypervisor:   binutils bzip2 cpp cpp7 createrepo_c dwz gcc gcc7 gettext-tools glibc-devel glibc-locale glibc-locale-base libasan4 libatomic1 libcilkrts5 libcreaterepo_c0 libctf-nobfd0 libctf0 libgomp1 libisl15 libitm1 liblsan0 libmodulemd2 libmpc3 libmpfr6 libmpx2 libmpxwrappers2 libtsan0 libubsan0 libxcrypt-devel libyaml-0-2 linux-glibc-devel make patch rpm-build tar xz
```
```
qemu.hypervisor: The following 2 packages are going to be REMOVED: …
```

fake conntrack cleanup

---

packages/node-image-base/base.packages

- Fixes: MTL-2149
Adds `python3-dmidecode` for CVT.

MTL-2149 Add python3-dmidecode

---

packages/node-image-kubernetes/base.packages

When helping NERSC last week, we noticed that the cmsdev test tool doesn't provide a list of valid tests to run when you ask it to show its usage message -- it is only visible when you specify an invalid test or omit the test argument. This changes that, so that you can get the information from the usage message itself.
No changes made to the tests themselves.
- [Source PR](https://github.com/Cray-HPE/cms-tools/pull/102)
- [csm manifest PR](https://github.com/Cray-HPE/csm/pull/2137)
- Resolves [CASMCMS-8549](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8549)
See source PR.
Low risk.

CASMCMS-8549: cmsdev: Add list of valid tests to --help output
