Cray-HPE/csm-rpms

- packages/cray-pre-install-toolkit/metal.packages
Release CSI with the fix for MTL-1555
> MTL-1555: release csi with k8s/routes fix

- packages/node-image-non-compute-common/base.packages
Resolves 
* CASMINST-3546 : csi pit validate for k8s has failed
> CASMINST-3546 main : csi pit validate for k8s has failed

- packages/compute-node.packages
- packages/cray-pre-install-toolkit/base.packages
- packages/node-image-non-compute-common/base.packages
Updated craycli version for SCSD sub-command changes.
* Resolves CASMHMS-5273
* This change completes CASHMS-5181
* local build machine
Ran a copy of the new SCSD on my build machine.  Ran the modified CLI
locally as well according to the CLI development guidelines.  Everything
worked as expected.
Low risk.
> Updated craycli version for SCSD sub-command changes.

- packages/cray-pre-install-toolkit/metal.packages
Latest release of CSI with the fix for CASMTRIAGE-2648
> CASMTRIAGE-2648: csi with fix

- packages/cray-pre-install-toolkit/metal.packages
CSI with the fix for CASMTRIAGE-2648
> CASMTRIAGE-2648: csi with the fix

- packages/cray-pre-install-toolkit/metal.packages
Latest cray-site-init 1.13.2-1.
> CASMINST-3647

- packages/cray-pre-install-toolkit/base.packages
> CASMINST-3699: release latest csi

- packages/cray-pre-install-toolkit/base.packages
Release CSI with the MTL-1429 changes
> MTL-1429: release csi containing upgrade logic

- packages/cray-pre-install-toolkit/base.packages
Need to add the PeerASN, MyASN, and MetalLBPoolName to SLS in order to be able to properly upgrade customizations.yaml from 1.0 to 1.2.   For upgrades we are using SLS for the source of truth of the system configuration.   SLS has most of what is needed for MetalLB but it is missing the ASNs and the pool names.     This also cleans things up in CSI for generating customizations.yaml in a fresh install.
DOES THIS CHANGE INVOLVE ANY SCHEME CHANGES?  N
REMINDER: HAVE YOU INCREMENTED VERSION NUMBERS? Y (.version and CHANGELOG.md)
REMINDER 2: HAVE YOU UPDATED THE COPYRIGHT PER hpe GUIDELINES: (C) Copyright 2014-2021 Hewlett Packard Enterprise Development LP    ? Y
LIST AND CHARACTERIZE RELATIONSHIP TO JIRA ISSUES AND OTHER PULL REQUESTS. BE SURE LIST DEPENDENCIES.
* Work required by …
> CASMNET-967:  Update CSI with ASN and pool name fields

- packages/node-image-kubernetes/base.packages
See original PR for details:
https://github.com/Cray-HPE/cms-tools/pull/23
Related manifest PR:
> CASMINST-3725: Fix typos in barebones boot test

- packages/cray-pre-install-toolkit/base.packages
- packages/node-image-non-compute-common/base.packages
Canu upgrade to 1.1.1
* Resolves 
CASMNET-1088
CASMNET-1089
CASMNET-1090
CASMNET-1099
CASMNET-1092
Hela
Ran CANU on Hela successfully. 
No
> Casmnet 1089,1088,1090,1099

- packages/cray-pre-install-toolkit/base.packages
Debug logic is preventing full run and has far too much output.
Bugfix CASMINST-3751
No risk, new logic already broken.
> Removed debug logging and break.

- packages/cray-pre-install-toolkit/base.packages
Debug logic is preventing full run and has far too much output.
Bugfix CASMINST-3751
No risk, new logic already broken.
> Bumped version of CSI.

- packages/cray-pre-install-toolkit/base.packages
Update looftsman package version in base packages livecd aka cray-pre-install-toolkit to 1.2.
_Summarize what has changed. Explain why this PR is necessary. What is impacted? Is this a new feature, critical bug fix, etc?_ Update of loftsman package for the livecd image to 1.2.0-1.
* Resolves [CASMINST-3830](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-3830)
* Change will also be needed in `already made'
* Future work required by 'N\A'
* Documentation changes required in 'N\A'
* Merge with/before/after 'N\A'
* …
> CASMINST-3830 update loftsman package verison to 1.2.0-1 for livecd

- packages/cray-pre-install-toolkit/base.packages
Update to the version of csi with the fix for CASMPET-5279
> CASMPET-5279: update version of csi

- packages/node-image-non-compute-common/base.packages
Removed hardcoded passwords from variables-livecd.yaml, and require user to provide the password for the admin user on the management switches via the SW_ADMIN_PASSWORD environment variable when running the LiveCD preflight checks and ncn-healthcheck test suites.
Removed unused/deprecated Goss tests that depended on switch_aruba.password and switch_mellanox.password Goss variables.
backwards compatible
* Resolves …
> (CSM 1.2) CASMPET-3996: New version of goss-servers

- packages/node-image-non-compute-common/base.packages
Removed hardcoded passwords from variables-livecd.yaml, and require user to provide the password for the admin user on the management switches via the SW_ADMIN_PASSWORD environment variable when running the LiveCD preflight checks and ncn-healthcheck test suites.
Removed unused/deprecated Goss tests that depended on switch_aruba.password and switch_mellanox.password Goss variables.
backwards compatible
* Resolves …
> (main) CASMPET-3996: New version of goss-servers

- packages/cray-pre-install-toolkit/base.packages
> CASMINST-3929

- packages/compute-node.packages
- packages/cray-pre-install-toolkit/base.packages
- packages/node-image-non-compute-common/base.packages
Adds a parameter to CFS to allow sessions to be created with arbitrary arguments passed to Ansible
* Resolves CASMCMS-7784
* Wasp
Ran CFS sessions without passthrough parameters, and with different combinations of parameters.
None
> CASMCMS-7784: Update CFS cli to add Ansible passthrough

- packages/cray-pre-install-toolkit/base.packages
> CASMINST-3935

- packages/node-image-non-compute-common/base.packages
Pull in goss RPMs with fixes for CASMINST-3274, CASMINST-3945, and CASMINST-3949
> Pull in goss RPMs with fixes for CASMINST-3274, CASMINST-3945, and CASMINST-3949

- packages/node-image-non-compute-common/base.packages
Needed by CASMNET-818 bican script(s)
* Resolves [CASMNET-1132](https://jira-pro.its.hpecorp.net:8443/browse/CASMNET-1132)
Installed the rpm on vshasta -- script dependencies were satisfied
* `vshasta`
Downloaded and installed the rpm
None
> Add pyroute2 package to ncn image for bican route script

- packages/cray-pre-install-toolkit/base.packages
https://github.com/Cray-HPE/cray-site-init/pull/119
> MTL-1600 Fixes kernel parameters for NCNS in 1.0-1.2 upgrades

- packages/node-image-non-compute-common/base.packages
- fix false positive for goss test check_ncn_uan_ip_dns.py
- update wording to out of test to reference python version instead of bash version
- fix false positive
- update reference to script to be python version instead of bash version
yes
CASMINST-3957
drax
_How were the changes tested and success verified? If schema changes were part of this change, how were those handled in your …
> Bugfix/casminst-3957-csm-1.2 - bumping goss test scripts version

- packages/node-image-non-compute-common/base.packages
During the csm 1.2 upgrade, cronjobs may get re-created because of too many failed attempts to start.
Postgresql cronjob based backup are expected to exist 24hr after the cluster is created. This window needs to be based on when the cronjobs were created (or re-created in the case of the upgrade) and not when the cluster was created.
_Is this change backwards incompatible, backwards compatible, or a backwards compatible bugfix? Yes
* Resolves [CASMINST-4030](issue link)
* Change will also be needed in `master`
vshasta
drax 
Verified on drax that the script passes as expected.  Some of the postgresql cronjobs had been re-created as part of the upgrade (but not all)
```
ncn-m001:~ # …
```
> CASMINST-4030 1.2 : TESTS - Kubernetes Postgresql Check that Automated Backups are Working

- packages/node-image-non-compute-common/base.packages
Need more than ten seconds for this test -- bumped to 60 seconds to give plenty of headroom.
* Resolves [CASMINST-4055](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4055)
```
ncn-w001:~ # export GOSS_BASE=/opt/cray/tests/install/ncn; goss -g /opt/cray/tests/install/ncn/tests/goss-k8s-console-services.yaml --vars=/opt/cray/tests/install/ncn/vars/variables-ncn.yaml validate
.
Total Duration: 6.203s
Count: 1, Failed: 0, Skipped: 0
```
* `hela`
Changed the timeout, ran fine (but finished in 6 seconds on hela)
Low
> New csm-testing for goss console pods test timeout

- packages/cray-pre-install-toolkit/base.packages
- packages/node-image-non-compute-common/base.packages
Bump Canu version
CASMINST-3986
Hela, Drax, VirtualEnv
> CASMINST-3986

- packages/cray-pre-install-toolkit/base.packages
> CASMINST-4061 change wicked  update version csm-rpms

- packages/cray-pre-install-toolkit/base.packages
See code PR for details:
https://github.com/Cray-HPE/pit-init/pull/19
> CASMINST-4040: bios-baseline.sh --check no longer changes BMC ipmitool settings

- packages/node-image-non-compute-common/base.packages
See PR for details: https://github.com/Cray-HPE/csm-testing/pull/200
> CASMINST-4072: goss test improvements

- packages/node-image-non-compute-common/base.packages
CASMINST-4000 
BGP test fix.
Goss rpm version bump.
> CASMINST-4000 main

- packages/node-image-non-compute-common/base.packages
CASMINST-4000 
BGP test fix.
Goss rpm version bump.
> CASMINST-4000 1.2

- packages/cray-pre-install-toolkit/base.packages
- packages/node-image-non-compute-common/base.packages
Bump CANU Version
CASMNET-1163
CASMNET-4051
CASMNET-1159
CASMNET-1160
CASMNET-998
Virtual Env
Hela
> CASMNET-1163

- packages/cray-pre-install-toolkit/base.packages
- Fixes #CASMINST-1172
The switches have been locked down in 1.2 to disallow ssh to the switches via the NMN.   However, the host records we create for the switches use the NMN IPs.  This changes both the fresh install and upgrade paths of CSI to use the HMN IPs for the switches in their host records.
Kind of tested on hela.  I used the hela seed files to run `csi config init` and verified that the host records in the generated data.json have the HMN IPs for the switches.
```
{
"ip": "10.254.0.2",
"aliases": [
"sw-spine-001"
]
},
{
"ip": "10.254.0.3",
"aliases": [
"sw-spine-002"
]
},
{
"ip": "10.254.0.4",
"aliases": [
"sw-leaf-001"
]
},
{
"ip": "10.254.0.5",
"aliases": [
"sw-leaf-002"
]
},
{
"ip": "10.254.0.6",
"aliases": [
"sw-leaf-003"
]
},
{
"ip": "10.254.0.7", …
```
> CASMNET-1172:  Update cray-site-init RPM to 1.16.3

- packages/cray-pre-install-toolkit/base.packages
> CASMNET-1165: release latest csi

- packages/node-image-non-compute-common/base.packages
Update csm-testing/goss-servers RPMs to 1.12.14 to pull in:
* CASMINST-4091
* CASMINST-4095
* CASMINST-4157
* CASMINST-4161
* CASMINST-4176
* CASMINST-4183
* CASMINST-4186
* CASMINST-4195
* CASMINST-4196
* CASMINST-4197
* CASMINST-4222
> Update csm-testing/goss-servers to 1.12.14

- packages/cray-pre-install-toolkit/base.packages
> CASMINST-4230

- packages/node-image-non-compute-common/base.packages
Call load balancer test after pit is rebooted, and services are fully deployed.
* Resolves [CASMINST-4250](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4250)
N/A -- no change to test, just moving to different suite
N/A
N/A
Low
> Move loadbalancer test to suite after pit reboot

- packages/cray-pre-install-toolkit/base.packages
- packages/node-image-non-compute-common/base.packages
Canu: Release 1.3.2 
**Quick summary:**
New feature: Customer custom config injection.
Both code and switch configuration bug fixes and updates.
**Detailed change log since last official release.**
```
Fix aruba banner output during canu validate
shutdown unused ports by default on aruba 6300+dell+mellanox
Removed the override feature
Add feature to inject custom configs into generated switch configs
Change Aruba banner from motd to exec
Reordered the configuration output so that vlans are defined before being applied to ports.
Fix Leaf-bmc naming corner case: leaf-bmc-bmc to leaf-bmc
Fix OSPF CAN vlan for 1.2 in full/tds
Fixed bug to allow canu to exit gracefully with sys.exit(1)
Add network test cases
Add network test cases for DNS and site connectivity
Fixed missing DNS from Aruba …
```
> update canu release to 1.3.2 in base.packages

- packages/cray-pre-install-toolkit/base.packages
> CASMINST-4419

- packages/cray-pre-install-toolkit/base.packages
This adds a function that will disable DHCP over the Shared NIC on HPE servers equipped with iLO5.
The new function checks the current DHCP setting and toggles it to False if it is not already set to that value.
Output shows that DHCP is enabled, so the tool will disable DHCP:
```bash
The running host [ncn-m001-mgmt] will have settings applied last.
Verifying 10 iLO/BMCs (non-compute nodes) match BIOS baseline spec.
================================
Checking ncn-s002-mgmt ... differs from spec
ipmitool usage: enabled
BMC Shared NIC DHCP: enabled
```
A re-run shows that DHCP is disabled:
```bash
The running host [ncn-m001-mgmt] will have settings applied last. …
```
> CASMINST-4430 Disable Shared NIC DHCP Requests

- packages/cray-pre-install-toolkit/metal.packages
Adds tpm2 rpms to the PIT as seen in https://github.com/Cray-HPE/csm-rpms/pull/313
* Partially implements MTL-1638
* local builds
RPMs exist.
```
rpm qa | grep tpm
```
Low, this just installs some rpms so they are available for further testing with 1.2
> MTL-1638 tpm for PIT

- packages/node-image-non-compute-common/metal.packages
Adds TPM tools and service.  For now, these are just in place to allow
* Partially implements MTL-1638
* `#redbull`
Checked that the service deploys disabled so as not to interfere with things until we can work out the other details.
```
ncn-w003:~ # systemctl status tpm2-abrmd.service
● tpm2-abrmd.service - TPM2 Access Broker and Resource Management Daemon
Loaded: loaded (/usr/lib/systemd/system/tpm2-abrmd.service; disabled; vendor preset: disabled)
Active: inactive (dead)
```
checked for the existence of tpm2 utilities:
```
ncn-w003:~ # tpm2
tpm2-abrmd                    tpm2_getekcertificate         tpm2_pcrallocate              tpm2_policyticket
tpm2_activatecredential       tpm2_getrandom                tpm2_pcrevent …
```
> MTL-1638 add tpm2 tools and service rpms

- packages/cray-pre-install-toolkit/base.packages
> update csi version

- packages/cray-pre-install-toolkit/base.packages
A subset of the generated data from `csi config init` needs to be merged into the site-init/customizations.yaml file. PIT Init calls `csi config init` before copying the generated files into place, but it fails to handle the merge into customizations.yaml. This changes fixes that gap by invoking yq to merge that newly generated data into customizatons.yaml. PIT Init will do this before patching the CA certificate. All that needs to happen now from a pit-init perspective is the CSI files must be in place, and site-init must be created.
The docs will still entail calling `csi config init`, and then creating site-init before calling pit-init. However this change …
> CASMINST-4458 Handle YQ Merge

- packages/cray-pre-install-toolkit/base.packages
- packages/node-image-non-compute-common/base.packages
> Revert "CASMNET-1518: CANU Release 1.5.6 (1.2)"

- packages/cray-pre-install-toolkit/base.packages
- Relates to CASMINST-4485
If /usr/bin/yq exists, it'll be a symlink not a file. The current -f test fails to find it if it exists. This change tests for its existence with command.
This also sets up the need for `CSM_PATH` only when `/usr/bin/yq` is not present.
```bash
pit:/var/www/ephemeral/prep # unset CSM_PATH
pit:/var/www/ephemeral/prep # /root/bin/pit-init.sh
Initializing the Pre-Install Toolkit
Exporting tokens
+ export 'mtoken=ncn-m(?!001)\w+-mgmt'
+ mtoken='ncn-m(?!001)\w+-mgmt'
+ export 'stoken=ncn-s\w+-mgmt'
+ stoken='ncn-s\w+-mgmt'
+ export 'wtoken=ncn-w\w+-mgmt'
+ wtoken='ncn-w\w+-mgmt'
+ set +x
= PIT Identification = COPY/CUT START =======================================
VERSION=1.5.9
TIMESTAMP=20220422220404
HASH=g560024e
2022/04/23 01:54:08 Using …
```
> CASMINST-4485 Minor update for handling /usr/bin/yq

- packages/cray-pre-install-toolkit/base.packages
> CASMPET-5563 update manifest

- packages/node-image-non-compute-common/base.packages
Update the `dns_records.py` script to use the NMN API gateway URL so the API call doesn't fail.
* Resolves [CASMNET-1539](https://jira-pro.its.hpecorp.net:8443/browse/CASMNET-1539) and [CAST-29864](https://jira-pro.its.hpecorp.net:8443/browse/CAST-29864)
* `wasp`
> CASMNET-1539 - Update dns_records.py API call to use the correct API gateway.

- packages/cray-pre-install-toolkit/base.packages
- Fixes MTL-1741
Fixes the pattern matching for the initrd.img.xz file to account for the image ID.
> MTL-1741 Fix pattern matching for initrd check

- packages/node-image-non-compute-common/base.packages
> CASMINST-4600: add lsscsi to NCNs

- packages/cray-pre-install-toolkit/base.packages
- Fixes MTL-1530
Produces a signed ilorest RPM. This includes a version bump.
> MTL-1530 build a signed ilorest from the new fork

- packages/cray-pre-install-toolkit/base.packages
- packages/node-image-non-compute-common/base.packages
CASMNET-1519, CASMNET-1541, CASMNET-1548
> CASMNET-1519, CASMNET-1541, CASMNET-1548

- packages/cray-pre-install-toolkit/base.packages
- packages/node-image-non-compute-common/base.packages
MTL-1747, CASMNET-1519, CASMNET-1541, CASMNET-1548
Paddle fixes.
> MTL-1747, CASMNET-1519, CASMNET-1541, CASMNET-1548

- packages/node-image-non-compute-common/base.packages
> CASMTRIAGE-3363 add updated bios/firmware test bump

- packages/cray-pre-install-toolkit/base.packages
- packages/node-image-non-compute-common/base.packages
CANU version bump.
CASMINST-4667
Redbull
> CASMINST-4667 main

- packages/cray-pre-install-toolkit/base.packages
- packages/node-image-non-compute-common/base.packages
CANU version bump.
CASMINST-4667
Redbull
> CASMINST-4667 1.2

- packages/cray-pre-install-toolkit/base.packages
Add BGP ASN # validation to CSI.
CASMINST-4671
> CASMINST-4671-1.2

- packages/cray-pre-install-toolkit/base.packages
Add BGP ASN # validation to CSI.
CASMINST-4671
> CASMINST-4671-main

- packages/node-image-non-compute-common/base.packages
> Revert "CASMINST-4683 1.2 : worker node upgrade failed - cray-console-data-postgres"

- packages/node-image-non-compute-common/base.packages
There was an issue that was fixed in 1.2 but not in 1.0 where the goss_platform_ca_certs_match_cloud_init can fail if the ca-certs in the local file are not ordered the same as in the BSS meta-data
The test requires that the data be sorted and then diff'ed.
This was hit during a 1.0.11 fresh install of SS611 TDS
_Is this change backwards incompatible, backwards compatible, or a backwards compatible bugfix?_ Yes
* Resolves [CASMPET-5684](https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-5684)
* Change will also be needed in NA
groot and drax
* Local …
> CASMPET-5684 1.0 : TESTS : Add sort fix to goss_platform_ca_certs_match_cloud_init

- packages/cray-pre-install-toolkit/base.packages
Source change: https://github.com/Cray-HPE/cray-site-init/pull/185
> MTL-1786: new CSI

- .github/workflows/shellcheck.yml
- build/create-index.sh
- build/update-packages.sh
- scripts/rpm-functions.sh
- scripts/update-package-versions.sh
> Add shellcheck to the release/1.2 branch

- packages/cray-pre-install-toolkit/base.packages
> CASMTRIAGE-3402-main

- packages/cray-pre-install-toolkit/base.packages
> CASMTRIAGE-3402

- packages/node-image-non-compute-common/base.packages
We've seen a few cases this week where if the preflight fails on SyncFailed, the test does not give link for remediation. This adds that info to the test.
* Resolves [CASMINST-4764](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-4764)
* Change will also be needed in NA
_How were the changes tested and success verified? If schema changes were part of this change, how were those handled in your upgrade/downgrade testing?_
- Were the …
> CASMINST-4764 1.3 : Still seeing the check for SynFailed failing - automated remediation is next step?

- packages/cray-pre-install-toolkit/base.packages
New CSI: https://github.com/Cray-HPE/cray-site-init/pull/201
* Resolves [CASMTRIAGE-3640](https://jira-pro.its.hpecorp.net:8443/browse/CASMTRIAGE-3640)
> CASMTRIAGE-3640: CSI 1.20.1

- packages/cray-pre-install-toolkit/base.packages
- Fixes: MTL-1836 CASMINST-4909
New cray-site-init and pit-init.
- https://github.com/Cray-HPE/pit-init/pull/46
- https://github.com/Cray-HPE/cray-site-init/pull/202
> CASMINST-4909 & MTL-1836

- packages/cray-pre-install-toolkit/base.packages
> CASMTRIAGE-3597 pit-nexus

- packages/cray-pre-install-toolkit/base.packages
- Fixes: CASMINST-5003
See: https://github.com/Cray-HPE/pit-init/pull/48
> CASMINST-5003 new pit-init

- packages/node-image-kubernetes/base.packages
- Fixes: https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5051
- Requires:
- Relates to:
This fixes an issue with the fix-spire-on-storage.sh script.
> CASMINST-5051 Bump utils to 1.3.1-1

- packages/node-image-non-compute-common/base.packages
This addresses a large number of problems related to the Goss tests. Without this fix, there are a number of failures we can expect to see.
I tested the changes on surtur.
See the source PR for details:
https://github.com/Cray-HPE/csm-testing/pull/345
I tested the changes on surtur.
Moderate risk in that there are a number of changes, but low risk in that without this there will be a lot of problems.
> CASMINST-5025: Numerous Goss testing fixes

- packages/cray-pre-install-toolkit/base.packages
- Fixes: CASMNET-1635, CASMTRIAGE-3780
> CASMNET-1635

- packages/node-image-kubernetes/base.packages
See source PR for details:
https://github.com/Cray-HPE/cms-tools/pull/42
https://github.com/Cray-HPE/csm/pull/1059
https://github.com/Cray-HPE/docs-csm/pull/2108
See source PR for details:
https://github.com/Cray-HPE/cms-tools/pull/42
Low risk. Small change.
> CASMCMS-8069: Barebones boot test should not disobey --xname argument

- packages/node-image-non-compute-common/metal.packages
- Relates to: MTL-1841
See: https://github.com/Cray-HPE/dracut-metal-mdsquash/pull/50
> MTL-1841 Forgo the bind mount

- packages/cray-pre-install-toolkit/base.packages
- Fixes: MTL-1868
See: https://github.com/Cray-HPE/pit-init/pull/49
> MTL-1868 new pit-init

- packages/node-image-non-compute-common/base.packages
- Fixes: [CASMINST-5169](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5169)
- Fixes: [CASMINST-5171](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5171)
CSM PR: https://github.com/Cray-HPE/csm/pull/1097
See source PRs for full details:
https://github.com/Cray-HPE/csm-testing/pull/351
https://github.com/Cray-HPE/csm-testing/pull/352
Tested on drax. See source PRs for full details:
https://github.com/Cray-HPE/csm-testing/pull/351
https://github.com/Cray-HPE/csm-testing/pull/352
Low risk and enables future improvements.
> CASMINST-5169/CASMINST-5171: Goss test server improvements

- packages/cray-pre-install-toolkit/base.packages
- Fixes: CASMISNT-4903
See: https://github.com/Cray-HPE/cray-site-init/pull/210
> CASMINST-4903 new cray-site-init

- packages/node-image-non-compute-common/base.packages
The current version of velero has a bug which causes a backup to be created when the backup schedule is created.
On installs, this causes the backup to be run before the service is fully healthy and thus the backup ends up PartiallyFailed.
This removes any such PartiallyFailed backup that were created within 10m of the backup schedule creation time. The test then continues to check for any remaining *Failed backups. Those would still need to be investigated, but the initial PartiallyFailed backup will not longer cause the test to fail and need to be remediated since that particular PartiallyFailed backup(s) will be deleted.
This fix will reduce the install time given it automatically remediates those PartiallyFailed backups that are a result of a velero bug before the test to check for …
> CASMINST-4278-1.3 : AUTOMATION: Find a solution/automated remediation/re-execute failed velero backups

- packages/node-image-non-compute-common/metal.packages
- Fixes: CASMINST-5103
See: https://github.com/Cray-HPE/dracut-metal-mdsquash/pull/48
> CASMINST-5103 Better lvm wipe logging

- packages/compute-node.packages
- packages/cray-pre-install-toolkit/base.packages
- packages/node-image-non-compute-common/base.packages
- Fixes: [SKERN-4460](https://jira-pro.its.hpecorp.net:8443/browse/SKERN-4460)
Version update for adding craycli nmd update.
- [  ] I have included documentation in my PR (or it is not required)
- [  ] I tested this on internal system (if yes, please include results or a description of the test)
- [  ] I tested this on a vshasta system (if yes, please include results or a description of the test)
Very low risks since version for craycli is the only thing got updated.
> SKERN-4460: updated version for craycli nmd command

- packages/compute-node.packages
- packages/extra.packages
- packages/node-image-non-compute-common/base.packages
Switches to builds that don't include dev.cray.com for cfs-trust, cfs-state-reporter, cf-ca-cert and cray-tftp
* Resolves CASMCMS-7971
* Resolves CASMCMS-8143
* Mug
Ran artifacts from the new builds and tested functionality. (No changes were expected).
None
> CASMCMS-7971: Update cfs and tftp services for build changes

- packages/compute-node.packages
- packages/cray-pre-install-toolkit/base.packages
- packages/node-image-non-compute-common/base.packages
- Fixes: [CASMHMS-5351](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-5351)
This introduces some risk since this change also brings in a newer version of X, but otherwise the original bugfix
is resolved and the overall risk of fatal failures is reduced.
> CASMHMS-5351: Fixed sls loadstate and dumpstate in the cray cli

- packages/cray-pre-install-toolkit/base.packages
- Fixes: CASMPET-5428
Fixes for `cephExporter` endpoints.
Brings in some dependency/library updates.
> CASMPET-5428 `cray-site-init`

- packages/node-image-kubernetes/base.packages
- Fixes: [CASMCMS-8087](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8087)
See source PR for details:
https://github.com/Cray-HPE/cms-tools/pull/50
Low risk.
> CASMCMS-8087: Add BOSv2 support to cmsdev test tool

- packages/cray-pre-install-toolkit/base.packages
- packages/node-image-non-compute-common/metal.packages
- Fixes: MTL-1876
These packages contain updates to support S3 pre-signed URLs, and they
support backwards compatibility with non-S3/pre-signed URL environments.
Includes new:
- `cray-site-init` https://github.com/Cray-HPE/cray-site-init/pull/232
- `dracut-metal-mdsquash` https://github.com/Cray-HPE/dracut-metal-mdsquash/pull/53
- `metal-ipxe` https://github.com/Cray-HPE/metal-ipxe/pull/49
- `pit-init` https://github.com/Cray-HPE/pit-init/pull/51
> MTL-1876 S3 Pre-Signed URL Support

- packages/cray-pre-install-toolkit/base.packages
> MTL 1876 wrong version; redo of MTL-1876

- packages/compute-node.packages
- packages/cray-pre-install-toolkit/base.packages
- packages/node-image-non-compute-common/base.packages
See https://github.com/Cray-HPE/csm/pull/1220
This should merge at the same time as these other PRs:
https://github.com/Cray-HPE/csm/pull/1225
https://github.com/Cray-HPE/csm/pull/1223
https://github.com/Cray-HPE/csm-rpms/pull/582
> CASMCMS-8192: Default the Cray CLI to v1 for BOS

- packages/node-image-pre-install-toolkit/base.packages
Minor fixes for facilitating the recovery paths from the PIT.
- https://github.com/Cray-HPE/pit-init/pull/53
- https://github.com/Cray-HPE/pit-init/pull/52
> MTL-1952 MTL-1953 New `pit-init`

- packages/cray-pre-install-toolkit/base.packages
- Fixes: MTL-1961
See: https://github.com/Cray-HPE/cray-site-init/pull/253
> MTL-1961 1.3

- packages/cray-pre-install-toolkit/base.packages
This reverts commit 888fa9111312f75a2206c3191bd9c326e255ea30.
- Fixes:
- Requires:
- Relates to:
> Revert "MTL-1961 1.3 (#618)"

- packages/cray-pre-install-toolkit/base.packages
> CASMNET-1876 1.3

- packages/node-image-pre-install-toolkit/base.packages
> CASMNET-1876

- packages/node-image-pre-install-toolkit/base.packages
- Fixes: MTL-1971
See: https://github.com/Cray-HPE/cray-site-init/pull/257
> MTL-1971 New CSI for 1.4 configs

- packages/node-image-common/base.packages
- packages/node-image-compute/base.packages
Updates the cli to pull in the latest CFS changes including support for configuration descriptions and naming the results of image customization.
* Resolves CASMCMS-8245
* CLI changes were tested locally
None
> CASMCMS-8245: Update craycli for CFS updates

- packages/node-image-pre-install-toolkit/base.packages
> MTL-1975: new pit-init

- packages/node-image-pre-install-toolkit/base.packages
Includes updated golang module dependencies.
- https://github.com/Cray-HPE/metal-basecamp/pull/28
- https://github.com/Cray-HPE/metal-basecamp/pull/29
- https://github.com/Cray-HPE/metal-basecamp/pull/30
- https://github.com/Cray-HPE/cray-site-init/pull/265
- https://github.com/Cray-HPE/cray-site-init/pull/266
- https://github.com/Cray-HPE/cray-site-init/pull/267
> Minor updates

- Jenkinsfile.github
- README.adoc
- packages/compute-node.packages
- packages/node-image-base/base.packages
- packages/node-image-base/google.packages
- packages/node-image-base/metal.packages
- packages/node-image-base/vagrant.packages
- packages/node-image-kubernetes/base.packages
- packages/node-image-kubernetes/google.packages
- packages/node-image-kubernetes/metal.packages
- packages/node-image-kubernetes/vagrant.packages
- packages/node-image-ncn-common/base.packages
- packages/node-image-ncn-common/google.packages
- packages/node-image-ncn-common/metal.packages
- packages/node-image-ncn-common/vagrant.packages
- packages/node-image-pre-install-toolkit/base.packages
- packages/node-image-pre-install-toolkit/google.packages
- packages/node-image-pre-install-toolkit/metal.packages
- packages/node-image-storage-ceph/base.packages
- packages/node-image-storage-ceph/google.packages
- packages/node-image-storage-ceph/metal.packages
- packages/node-image-storage-ceph/vagrant.packages
- Fixes: MTL-2034
- Relates to: MTL-2033
This creates a `node-image-base` folder with lists containing packages we want on every node-image build (e.g. application, compute, non-compute).
This also renames `node-image-common` to `node-image-ncn-common` as to emphasize its specificity to the `ncn-common` layer itself.
The new `node-image-base` folder was de-duped against the previously used `node-image-common` folder, and should not have any overlap.
As the application and compute images are developed and factored into the node-images repository, the `node-image-base` package lists are expected to have some refactoring (e.g. moving packages _out_ and back into `node-image-ncn-common`, or adding new packages).
> MTL-2034 Create base/general package lists

- packages/node-image-pre-install-toolkit/base.packages
- Fixes: CASMINST-5622 MTL-1657
> CASMINST-5622 `basecamp` and MTL-1657 `metal-ipxe`

- packages/node-image-base/base.packages
- packages/node-image-compute/base.packages
Implements all current PCS APIs as pretty much a pass through. Hostlist expansion done by the CLI before calling the PCS API.
- Fixes: [CASMHMS-4619](https://jira-pro.its.hpecorp.net:8443/browse/CASMHMS-4619)
Added CLI for PCS
* Simulated Shasta environment
Manually executed all CLI options based on the unit tests that were created. Powered simulated nodes on and off, power capped simulated nodes. Verified expected interaction with PCS was working as expected.
None
> Add new CrayCLI that supports PCS

- Jenkinsfile.github
- packages/node-image-application/base.packages
- packages/node-image-application/google.packages
- packages/node-image-application/metal.packages
- packages/node-image-application/vagrant.packages
https://jira-pro.its.hpecorp.net:8443/browse/MTL-2004
Adds packages for application node images.
Low risk, but the package list will likely need to be scaled back down the road.
> MTL-2004 add application node packages

- packages/node-image-pre-install-toolkit/base.packages
bump csi version
- Fixes: MTL-1939
> MTL-1939: bump csi version

- packages/node-image-pre-install-toolkit/base.packages
follow-up to #668 , it was more behind than I thought.
> .29 not .28

- packages/node-image-pre-install-toolkit/base.packages
> Revert ".29 not .28"

- packages/node-image-application/base.packages
- packages/node-image-compute/base.packages
- packages/node-image-ncn-common/base.packages
- Fixes: MTL-2015
Not needed since we do not use DVS.
> MTL-2015 Remove `cray-spire-dracut`

- packages/node-image-pre-install-toolkit/base.packages
CASMMON-208: Automate prometheus, grok exporter and grafana gets instantiated automatically on Combined Install Media LiveDVD
* Resolves - https://jira-pro.its.hpecorp.net:8443/browse/CASMMON-208
Gamora-csm-pit
gamora-ncn-m001-pit: # podman ps
CONTAINER ID  IMAGE                                                                                   COMMAND               CREATED        STATUS …
> CASMMON-208: Automate prometheus, grok exporter and grafana gets  instantiated automatically on PIT node.

- packages/node-image-compute/base.packages
Removes spire packages specifically for compute images.
> MTL-2012: Remove spire packages

- .github/workflows/shellcheck.yml
- Relates to: https://github.com/Cray-HPE/csm-rpms/pull/667#issuecomment-1346834854
Use shellcheck workflow from docs-csm in order to only scan changed files.
> Fix shellcheck

- packages/node-image-pre-install-toolkit/base.packages
> CASMINST-5757 Revert "CASMMON-208: Automate prometheus, grok exporter and grafana gets  instantiated automatically on PIT node."

- packages/node-image-application/base.packages
- packages/node-image-compute/base.packages
- packages/node-image-ncn-common/base.packages
- repos/compute.template.repos
- repos/cray.template.repos
Brings in COS 2.5 with spire-agent 1.4.0.
> CASMPET-5081 COS 2.5

- packages/node-image-application/base.packages
- packages/node-image-ncn-common/base.packages
Updates all CFS rpms to the latest for consitency.  This pulls in build changes and a bug fix for cfs-debugger.
* Resolves CASMCMS-8379
Testing was done as part of the code change PRs.  See those for more information.
None
> CASMCMS-8379: Fix CFS rpm versions (1.4)

- packages/node-image-base/base.packages
- Fixes: [CASMCMS-8380](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8380)
- [main backport manifest PR](https://github.com/Cray-HPE/csm-rpms/pull/713)
- [csm 1.4 manifest PR](https://github.com/Cray-HPE/csm/pull/1680)
See source PRs for details:
- [craycli PR](https://github.com/Cray-HPE/craycli/pull/65)
- [CFS PR](https://github.com/Cray-HPE/config-framework-service/pull/58)
Minor fixes to Cray CFS CLI formatting and language.
Low risk -- no functional changes.
> CASMCMS-8380: Minor language and formatting corrections to CFS Cray CLI

- packages/node-image-ncn-common/base.packages
Updates the cfs-debugger to fix an issue where a dependency was missing.
* Resolves CASMCMS-8395
* Locally/venv
Installed package in a clean venv and verified dependencies.
None
> CASMCMS-8395: Update cfs-debug to fix install dependency (1.4)

- packages/node-image-ncn-common/base.packages
Updates the cfs-debugger to fix an issue where a dependency was missing.
* Resolves CASMCMS-8395
* Locally/venv
Installed package in a clean venv and verified dependencies.
None
> CASMCMS-8395: Update cfs-debug to fix install dependency

- packages/node-image-kubernetes/base.packages
- packages/node-image-ncn-common/base.packages
* Fixes: [CASMINST-5874](https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5874)
* Fixes: [CASMCMS-8397](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8397)
* Relates to: [CASMCMS-8396](https://jira-pro.its.hpecorp.net:8443/browse/CASMCMS-8396)
* [csm PR](https://github.com/Cray-HPE/csm/pull/1734)
Updates to tests to handle CRUS removal.
Low risk. Tests will fail without this.
> CASMINST-5874/CASMCMS-8397: CRUS removal

- packages/node-image-application/base.packages
- packages/node-image-compute/base.packages
- packages/node-image-ncn-common/base.packages
- Relates to: https://github.com/Cray-HPE/csm-rpms/pull/720
More COS alignments for COS 2.5 are in.
> Further COS alignment

- packages/node-image-pre-install-toolkit/base.packages
> CASMNET-2018 1.4

- packages/node-image-pre-install-toolkit/base.packages
> CASMNET-2018 main

- packages/node-image-pre-install-toolkit/base.packages
https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5966
Bump canu version
> CASMINST-5966 1.4

- packages/node-image-pre-install-toolkit/base.packages
https://jira-pro.its.hpecorp.net:8443/browse/CASMINST-5966
Bump canu version
> CASMINST-5966 main

- packages/node-image-pre-install-toolkit/base.packages
- Fixes: MTL-2080
https://github.com/Cray-HPE/pit-init/pull/66
> MTL-2080 New `pit-init`

- packages/node-image-base/base.packages
- Fixes: MTL-2091
New kernel `5.14.21-150400.24.46.1`
New mozilla-nss packages for SUSE-SU-2023:0119-1.
> MTL-2091 SUSE-SU-20230433-1

- packages/node-image-pre-install-toolkit/base.packages
- Fixes: MTL-2105
No longer used, repository is archived.
> MTL-2105 Remove `metal-net-scripts`

- packages/node-image-application/base.packages
> update spire-agent version for application image

- packages/node-image-application/base.packages
- packages/node-image-compute/base.packages
https://jira-pro.its.hpecorp.net:8443/browse/CASM-3071
adds needed packages for compute images and updates spire-agent for compute and application images
> CASM-3071 add packages

- packages/node-image-kubernetes/base.packages
- packages/node-image-ncn-common/base.packages
Main backport of https://github.com/Cray-HPE/csm-rpms/pull/780
> CASMCMS-8473: Run tftp file transger subtest on workers not masters

- packages/node-image-pre-install-toolkit/base.packages
- Fixes:
- Requires:
- Relates to:
https://github.com/Cray-HPE/cray-site-init/pull/298
> CASMTRIAGE-5072

- packages/node-image-kubernetes/base.packages
Would like to reuse some etcd scripting from platform-utils for newer goss tests.
- Supports: https://jira-pro.its.hpecorp.net:8443/browse/CASMPET-6397
Low
> Bump pre-installed version of platform-utils for 1.5

- packages/node-image-application/base.packages
- packages/node-image-base/base.packages
- packages/node-image-compute/base.packages
- packages/node-image-ncn-common/base.packages
- Fixes: MTL-2014
Update `spire-agent` to 1.5.5, and use the new CSM built `spire-agent` package. This package can be used for all mediums, and no longer needs to be defined in 3 places.
> MTL-2014 `spire-agent` 1.5.5

- packages/node-image-kubernetes/base.packages
Main backport of https://github.com/Cray-HPE/csm-rpms/pull/791
> CASMCMS-8479/CASMCMS-8480: cmsdev: Add feature to list available tests; fix minor bug 

- packages/node-image-application/base.packages
- packages/node-image-base/base.packages
- packages/node-image-compute/base.packages
- packages/node-image-ncn-common/base.packages
> Revert "MTL-2014 `spire-agent` 1.5.5"

- packages/node-image-application/base.packages
- packages/node-image-base/base.packages
- packages/node-image-compute/base.packages
- packages/node-image-ncn-common/base.packages
This reverts commit 9194d490e5cad7a445f2039997e69a4bcda5c002.
Brings in spire-1.5.5.
> Revert "Revert "MTL-2014 `spire-agent` 1.5.5" (#793)"

- packages/node-image-kubernetes/base.packages
Small message fixes/improvements to cmsdev test tool. Because of the minor nature, and given that it is getting late in CSM 1.4, I am not planning to backport this.
- [source PR](https://github.com/Cray-HPE/cms-tools/pull/90)
- [csm manifest PR](https://github.com/Cray-HPE/csm/pull/2058)
See source PR for details.
Low risk -- only message changes.
> CASMCMS-8498: cmsdev: Fix typo in message; improve some message details

- packages/node-image-kubernetes/base.packages
Backport of https://github.com/Cray-HPE/csm-rpms/pull/809
> CASMCMS-8502: cmsdev: Update dependencies to resolve CVEs

- packages/node-image-kubernetes/base.packages
Minor simplifcations to BOS test to avoid potential false failures.
[csm 1.4 manifest PR](https://github.com/Cray-HPE/csm/pull/2080)
I tested on wasp to verify that the BOS test still worked, and to verify that no regression bugs were introduced.
Small change. Worth the risk to avoid BOS false failures.
> CASMCMS-8514: cmsdev: Simplify BOS test

- packages/node-image-kubernetes/base.packages
Main backport of https://github.com/Cray-HPE/csm-rpms/pull/820
> CASMCMS-8529: cmsdev: Provide additional debug information on failure

- packages/node-image-base/base-x86_64.packages
- Fixes: #819 
- Relates to: #827 
#827 removed the qlogic driver from #819.
> MTL-2140 shuffle removed qlogic driver

- packages/node-image-base/base.packages
- Fixes:
- Requires:
- Relates to:
> CASMTRIAGE-5282: update craycli

- README.md
Adds links to the readme to better direct users landing at this repo.
> CASMINST-4571 Add links
